### ISSUE TITLE
How to implement portrait video editing?

### ISSUE THREAD

**Issue by Yao-Yee** [KwaiVGI/LivePortrait#102]
That means how to drive a video instead of a single image?
like this video in the https://liveportrait.github.io/

https://github.com/KwaiVGI/LivePortrait/assets/76864107/97fe24e6-3520-43e7-8e88-8d48185e2bee

**Comment by simplyexperimental** [comment]
As far as I know the code for that is not released.
Someone did modify the code to make it do that so it is possible but I think for now it's not officially out until further notice.

**Comment by zzzweakman** [comment]
Just pull the latest updates to enjoy the new video editing features :)  @simplyexperimental @Yao-Yee
