### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Sheben11** [KwaiVGI/LivePortrait#103]
Hey, I got this error (FileNotFoundError: [WinError 2] The system cannot find the file specified). How can I solve it?

![image](https://github.com/KwaiVGI/LivePortrait/assets/175313067/7568b5e6-dfe2-43a4-8fb6-bce14543fe41)

**Comment by FurkanGozukara** [comment]
Most likely missing ffmpeg : https://youtu.be/-NjNy7afOQ0?si=BvOd3QPvhY0zQ0Yf
