### ISSUE TITLE
can not fetch mask_template.png when do lfs pull

### ISSUE THREAD

**Issue by Phyki52** [KwaiVGI/LivePortrait#11]
An error was caused by the missing file: src\utils\resources\mask_template.png

**Comment by cleardusk** [comment]
Thanks for your attention. Due to the bandwidth limit of github, I remove lfs in the newest main branch.

You can try to clone the repo again 😊

**Comment by cleardusk** [comment]
@Phyki52 Can you try to clone the repo again? It seems to work now.

**Comment by Phyki52** [comment]
> @Phyki52 Can you try to clone the repo again? It seems to work now.

The issue has been resolved, and the example can now be reproduced normally. Thank you.
