### ISSUE TITLE
Is it normal to be 6 times slower on  rtx 3070?

### ISSUE THREAD

**Issue by garbe-github-support** [KwaiVGI/LivePortrait#112]
windows 11
RTX 3070

nvcc:  
Cuda compilation tools, release 12.2, V12.2.128
Build cuda_12.2.r12.2/compiler.33053471_0
torch:
Name: torch
Version: 2.2.0+cu121

![image](https://github.com/KwaiVGI/LivePortrait/assets/131808107/12efe35a-1a7f-45a7-b016-f82c6398c18b)

Are there any good optimization methods?

**Comment by zzzweakman** [comment]
> windows 11 RTX 3070
> 
> nvcc: Cuda compilation tools, release 12.2, V12.2.128 Build cuda_12.2.r12.2/compiler.33053471_0 torch: Name: torch Version: 2.2.0+cu121
> 
> ![image](https://private-user-images.githubusercontent.com/131808107/347902230-12efe35a-1a7f-45a7-b016-f82c6398c18b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTcyMTgsIm5iZiI6MTcyMDc1NjkxOCwicGF0aCI6Ii8xMzE4MDgxMDcvMzQ3OTAyMjMwLTEyZWZlMzVhLTFhN2YtNDVhNy1iMDE2LWY4MmM2Mzk4YzE4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwNDAxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGQwMTg3M2E4YWM0Y2E3OWM3ZmEyYTY1M2QyNWFkNDg3NDgxZjU2ZWQ2Y2M4ZmFjZjcwZTRhYWJmZmZmYWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jEM6NJNFZpUZixTiMF94VDLkkWTBNimbJ2E1kV90naI)
> 
> Are there any good optimization methods?

Thank you for your attention. To accelerate generation speed, you can consider using the [motion template](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#template-making) in inference.py. This method can be 20% to 30% faster than using Gradio : )

**Comment by zzzweakman** [comment]
Hi, we have now added an acceleration method for Gradio. You can pull the latest update and try using the parameter --flag_do_torch_compile. @garbe-github-support

**Comment by FurkanGozukara** [comment]
Torch compile doesn't exists on Windows yet as far as I know

I should test this on cloud Ubuntu

**Comment by garbe-github-support** [comment]
> 该在云 Ubuntu 上测试

[Thank you very much](https://github.com/KwaiVGI/LivePortrait/issues/112#)
