### ISSUE TITLE
How to use --no-flag-use-half-precision (FP32) in Gradio App

### ISSUE THREAD

**Issue by MarsEverythingTech** [KwaiVGI/LivePortrait#115]
Hello,

How can I use the no half precision argument (or use FP32) in the Gradio App (app.py). Do I just change the "flag_use_half_precision: bool = True" to "False" in the argument_config.py file, or there are other things I must do to make it work?

Thanks in advance

**Comment by cleardusk** [comment]
Change to code as you did, or just `python app.py --no_flag_use_half_precision`
