### ISSUE TITLE
How to: Portrait video editing with stitching? 

### ISSUE THREAD

**Issue by bigandtallrecords** [KwaiVGI/LivePortrait#118]
Hello, 

Love the results I'm getting so far. But after much trial and error in comfyui and your grado interface I can't figure how you've attached the driver result to the motion of another video. If you have any insights or instructions on a comfyui workflow or whatever workflow to achieve that I would be very happy!

Thank you, 
Daniel

**Comment by cleardusk** [comment]
Thanks for your attention. We have not digged into the comfyui implementations. We will try to provide an implementation of video editing in next few days!

**Comment by zzzweakman** [comment]
The video editing feature is now available. You can check it out [here](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#-updates).
