### ISSUE TITLE
Adapt to animal face 🐱

### ISSUE THREAD

**Issue by ShiJiaying** [KwaiVGI/LivePortrait#119]
Hi，

I’ve made some updates to the project and would like to share. Below are the details of the changes I’ve made:

- Easy to ues LivePortrait on animal face
- X-Pose for keypoints

Here is the Git repository with my updates: [LivePortrait](https://github.com/ShiJiaying/LivePortrait)
![output5](https://github.com/user-attachments/assets/66097cda-2fe4-44c6-955b-32705b55f9d3)

**Comment by cleardusk** [comment]
Amazing. I have checked the training data again and confirmed that there is no animal data for this released model 🤣

**Comment by ShiJiaying** [comment]
> Amazing. I have checked the training data again and confirmed that there is no animal data for this released model 🤣

Without animal data, the result is quite good! 
In my test, the eyes can basically be controlled very well, but human teeth may  appear when animal’s mouth opens^ ^ .  The implicit keypoints help a lot!

**Comment by Inferencer** [comment]
> > Amazing. I have checked the training data again and confirmed that there is no animal data for this released model 🤣
> 
> Without animal data, the result is quite good! In my test, the eyes can basically be controlled very well, but human teeth may appear when animal’s mouth opens^ ^ . The implicit keypoints help a lot!

If the animals teeth are present on the source photo then the teeth should be correct in theory even on this model. You would have to ensure the driving vids first frame matches the open mouth though which may be cumbersome depending on the dogs mouth openness even if retargeting the first frame of the driving vid.

**Comment by mocmocmoc** [comment]
> but human teeth may appear when animal’s mouth opens

Please post vid, I need to see this 😂

**Comment by garbe-github-support** [comment]
great work

**Comment by Inferencer** [comment]
> > but human teeth may appear when animal’s mouth opens
> 
> Please post vid, I need to see this 😂


https://github.com/user-attachments/assets/933f7cd0-3c70-4f96-9b92-871acd87087b

I have an example of this

**Comment by ShiJiaying** [comment]
> > but human teeth may appear when animal’s mouth opens
> 
> Please post vid, I need to see this 😂



https://github.com/user-attachments/assets/64313022-c12b-4226-a93b-30c319ea4d0e

It is a badcase of wrong mouth keypoints and no teeth in the source animal pic.

**Comment by markyfsun** [comment]
It seems that if the character in the source picture has an open mouth, the teeth problem is resolved.
BTW, it can be generalized to humanoid characters like furry.
https://github.com/user-attachments/assets/184d57c1-747e-4fc5-b088-ce788588c2e1

**Comment by cleardusk** [comment]
Refer to the updates: https://github.com/KwaiVGI/LivePortrait/blob/main/assets/docs/changelog/2024-08-02.md
