### ISSUE TITLE
about “ Portrait video editing with stitching‘’ part

### ISSUE THREAD

**Issue by shangshangdyx** [KwaiVGI/LivePortrait#12]
Hey, you guys are just incredibly awesome! 🌟 This is hands down the best project I've come across recently. The test results are flawlessly perfect! 📊💯 I checked out the sections on your homepage about 'Portrait video editing with stitching' and 'Generalization to Animals'. 🐶🎨 Are there any release plans for these features

**Comment by cleardusk** [comment]
Stay tuned, but it may take several days or more : - )

**Comment by cleardusk** [comment]
The animals part maybe not released due to the inside restrictions : |
