### ISSUE TITLE
The --flag_do_torch_compile does not work on windows

### ISSUE THREAD

**Issue by Lesteriax** [KwaiVGI/LivePortrait#124]
Using flag --flag_do_torch_compile does not work on windows as it requires triton. 

pip install triton==2.3.0
ERROR: Could not find a version that satisfies the requirement triton==2.3.0 (from versions: none)
ERROR: No matching distribution found for triton==2.3.0

is there a workaround for this? or just don't use the flag at all?

**Comment by FurkanGozukara** [comment]
Yes torch compile not available on Windows

**Comment by Lesteriax** [comment]
how about this? https://github.com/triton-lang/triton/pull/4045

**Comment by FurkanGozukara** [comment]
there is triton pre compiled wheels

but i think still would not work. my auto installers install it i will test it later hopefully. currently i am on vacation
