### ISSUE TITLE
Live-Portrait ONNX model 

### ISSUE THREAD

**Issue by aihacker111** [KwaiVGI/LivePortrait#126]
This is the link to HuggingFace model id and Github code demo for running project with onnx model which I convert completed 5 original models 

<img width="367" alt="Screenshot 2024-07-12 at 19 03 10" src="https://github.com/user-attachments/assets/75de87b9-975a-4711-8f18-f94cea0c6e97">

I fixed the Grid Sample 5D error and successfully converted the Warping model via ONNX. Besides, other models all work fine and fast 

Live Portrait ONNX: https://huggingface.co/myn0908/Live-Portrait-ONNX
Github repo for running my ONNX: https://github.com/aihacker111/Efficient-Live-Portrait

Thank you @cleardusk  and your team for great project

**Comment by zzzweakman** [comment]
Thank you very much for your contribution! Could you please provide the test results for the inference speed? @aihacker111

**Comment by Sunitha-Thomas** [comment]
@aihacker111 
Thanks for the onnx models it worked great. But when i ran your onnx export [script](https://github.com/aihacker111/Efficient-Face2Vid-Portrait/blob/main/experiments/portrait2onnx_warping_models.py) but not working. 
`torch.onnx.errors.OnnxExporterError: Unsupported: ONNX export of operator GridSample with 5D volumetric input. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues
` this error again, how to fix?

**Comment by aihacker111** [comment]
@Sunitha-Thomas It's very easy than you though, just reduce your torch version and make sure it < version 2.0.0 -> it'll work

**Comment by aihacker111** [comment]
@zzzweakman  Yeah, sure bro
This is the process time when run full original pytorch models

<img width="519" alt="Screenshot 2024-07-12 at 20 16 56" src="https://github.com/user-attachments/assets/932360b1-8b17-4373-a135-6f8fb650e388">

This run on 354 frames with more than 1 hour
And This is the process time when run full onnx models

<img width="494" alt="Screenshot 2024-07-12 at 20 18 56" src="https://github.com/user-attachments/assets/5b9969f7-ab1a-4cc1-8cc7-fa9800b45f9a">

At the same number of frames and inputs, onnx model is boosting x2 faster 

Noted: I'm tested all of this on Apple Silicon M1 Pro CPU and not using CUDA , not change anything

**Comment by harisreedhar** [comment]
@aihacker111 Are you kidding me? Now It worked like charm. I spend 2 days on it. why on earth the latest pytorch doesn't export this

**Comment by aihacker111** [comment]
Oh for the explain of the question: Why the latest pytorch and onnx version is raising Grid Sample 5D model, 
I'm checking the function convert in ONNX and seem like it's a bug of Microsoft, it's block when the Convolution pass to the Converting Function -> this is a reason that cannot converted, but in the lower version Pytorch (example: Torch 1.13.0)
Torch and ONNX lib is matching everything , seem like we have to back door

**Comment by aihacker111** [comment]
@Sunitha-Thomas already fixed Grid Example 5D in my source code , you can pull or git clone again

**Comment by aihacker111** [comment]
@juntaosun please show me the full scripts

**Comment by aihacker111** [comment]
@juntaosun thank you , I'll check it later

**Comment by aihacker111** [comment]
@juntaosun only enable cuda , the warping model doesn't run ? , how about CPU

**Comment by aihacker111** [comment]
@juntaosun  Thank you,  I know where is the bug

**Comment by Echolink50** [comment]
Is this working properly. How do we run it? Just swap the models out or is there more to it? Thanks

**Comment by aihacker111** [comment]
@Echolink50 , git my repo , use can run it

**Comment by aihacker111** [comment]
@juntaosun hey bro , can you check and help me fix the result video is reversed with original video , something mistake in the code

**Comment by noname0121** [comment]
> @Echolink50 , git my repo , u can run it
Can you give more detailed instructions with a video?
I just downloaded git clone with the address you gave and don't know what to do anymore

**Comment by noname0121** [comment]
> @aihacker111 , git my repo , u can run it
Can you give more detailed instructions with a video?
I just downloaded git clone with the address you gave and don't know what to do anymore

**Comment by aihacker111** [comment]
@juntaosun please give me your email for adding to my repo

**Comment by aihacker111** [comment]
@noname0121 I will update readme later , please wait we need to clean all the code for easy to use

**Comment by noname0121** [comment]
> @aihacker111 I will update readme later , please wait we need to clean all the code for easy to use

Thank you very much, have a nice day

**Comment by henryruhs** [comment]
@aihacker111 Author of FaceFusion here, thanks for making this public. We need more people like you in the OS scene.

**Comment by aihacker111** [comment]
@henryruhs  Thank you so much, I'm really like your FaceFusion repo , it help me much during my AI engineer Journey ^_^ . I'm plan to convert to TensorRT for optimizing all of this model that help everyone can run it. Thank you

**Comment by aihacker111** [comment]
@juntaosun I'm checked relate to it, hey can you give me a mail, you can modify and push on my repo for easy to work

**Comment by aihacker111** [comment]
https://github.com/user-attachments/assets/259adee9-9d04-4224-b5bb-868bbd392ba7

this output is from the option webcam, so clearly it's related to warping.onnx , maybe I'm setting key with wrong output, let me check

**Comment by aihacker111** [comment]
@juntaosun  😂😂😂😂😂 onnx's output never ceases to surprise us as long as the arrays are shuffled

**Comment by Echolink50** [comment]
IS this working on WIndows? Are you all able to use the gradio app.py from Liveportrait?

**Comment by aihacker111** [comment]
@Echolink50 not yet, I and @juntaosun is still cleaning the code and will update as pull request for this project , but the inference code is working, you can try it on window, macos and linux

**Comment by Echolink50** [comment]
Ok. I am trying to install now. I tried to install just like Liveportrait but its saying things can't install in python 3.9 venv? Do I need to use python 3.10 venv?

**Comment by aihacker111** [comment]
@Echolink50 you can use my repo

**Comment by aihacker111** [comment]
@juntaosun Help me testing on real-time and show the fps . Thank you

**Comment by Echolink50** [comment]
I am. Still trying to install. I got error

ERROR: Ignored the following yanked versions: 2.6, 2.6.1
ERROR: Ignored the following versions that require a different python version: 3.3 Requires-Python >=3.10; 3.3rc0 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement networkx==3.3 

Do I need python 3.10 venv?

**Comment by aihacker111** [comment]
@Echolink50  yeah, you should create env by conda , it's stable

**Comment by aihacker111** [comment]
ONNX model is now working stable and faster, tomorrow I will clean and debug some code for enhance quality code, 
This is a final ONNX model demo for this project 

https://github.com/user-attachments/assets/0716a9f3-531b-4876-af2d-afe54b04e2ef

**Comment by Echolink50** [comment]
Got it working. Its not using the GPU for some reason. Windows 10, RTX 2060 12GB. Says its going to take 48 minutes to run one of the demos. The main LIveportrait branch takes only a few seconds. When you post the debugged git could you also give a few basic install instructions or explain how the install differs from the main branch. Thanks

**Comment by galigaligo** [comment]
> 一切正常，感谢您的贡献！❤️❤️❤️ 它现在非常快，至少比 CUDA 上的原始代码快 3 倍！👍👍👍
> 
>  s7--s7_concat.mp4

我测试了下，3060显卡，CUDA11.8
ONNX+CUDA 测试275帧 154.56s
pytorch+CUDA 测试275帧  144.68s
我的怎么更慢了呢....

**Comment by kitckso** [comment]
> > 一切正常，感谢您的贡献！❤️❤️❤️ 它现在非常快，至少比 CUDA 上的原始代码快 3 倍！👍👍👍
> > 
> >  s7--s7_concat.mp4
> 
> 我测试了下，3060显卡，CUDA11.8
> ONNX+CUDA 测试275帧 154.56s
> pytorch+CUDA 测试275帧  144.68s
> 我的怎么更慢了呢....
> 

I'm using 3060 too. I haven't try ONNX, but I tested 2xx frames with pytorch only takes 18s, seems your speed is abnormal.

**Comment by Echolink50** [comment]
> > > 一切正常，感谢您的贡献！❤️❤️❤️ 它现在非常快，至少比 CUDA 上的原始代码快 3 倍！👍👍👍
> > > s7--s7_concat.mp4
> > 
> > 
> > 我测试了下，3060显卡，CUDA11.8
> > ONNX+CUDA 测试275帧 154.56s
> > pytorch+CUDA 测试275帧  144.68s
> > 我的怎么更慢了呢....
> 
> I'm using 3060 too. I haven't try ONNX, but I tested 2xx frames with pytorch only takes 18s, seems your speed is abnormal.

The size of the inputs seem to affect the speed.

**Comment by x4080** [comment]
Hi, is your repo work for apple silicon too ?

**Comment by kitckso** [comment]
> > > > 一切正常，感谢您的贡献！❤️❤️❤️ 它现在非常快，至少比 CUDA 上的原始代码快 3 倍！👍👍👍
> > > > s7--s7_concat.mp4
> > > 
> > > 
> > > 我测试了下，3060显卡，CUDA11.8
> > > ONNX+CUDA 测试275帧 154.56s
> > > pytorch+CUDA 测试275帧  144.68s
> > > 我的怎么更慢了呢....
> > 
> > 
> > I'm using 3060 too. I haven't try ONNX, but I tested 2xx frames with pytorch only takes 18s, seems your speed is abnormal.
> 
> The size of the inputs seem to affect the speed.

Seems model input is 256x256, image will crop and resize before process, so it shouldn’t affect too much?

**Comment by galigaligo** [comment]
> > 一切正常，感谢您的贡献！❤️❤️❤️ 它现在非常快，至少比 CUDA 上的原始代码快 3 倍！👍👍👍
> > s7--s7_concat.mp4
> 
> 我测试了下，3060显卡，CUDA11.8 ONNX+CUDA 测试275帧 154.56s pytorch+CUDA 测试275帧 144.68s 我的怎么更慢了呢....

量化版本，

> > > 一切正常，感谢您的贡献！❤️❤️❤️ 它现在非常快，至少比 CUDA 上的原始代码快 3 倍！👍👍👍
> > > s7--s7_concat.mp4
> > 
> > 
> > 我测试了下，3060显卡，CUDA11.8
> > ONNX+CUDA 测试275帧 154.56s
> > pytorch+CUDA 测试275帧  144.68s
> > 我的怎么更慢了呢....
> 
> I'm using 3060 too. I haven't try ONNX, but I tested 2xx frames with pytorch only takes 18s, seems your speed is abnormal.

统一使用s10.jpg和d8.mp4测试，一共275帧，
pytroch+cuda, 全部循环时长（包含get_kp_info、stitching、parse_output等）用时45s,
如果只计算warping_module和spade_generator用时7.76s
`
mtime=0
start_time = time.time()
for i in track(range(n_frames), description='Animating...', total=n_frames):
            start_time2 = time.time()
            out = self.live_portrait_wrapper.warp_decode(f_s, x_s, x_d_i_new)
            end_time2 = time.time()
            haoshi += (end_time2 - start_time2)
end_time = time.time()
print("frams",n_frames,"all time:", end_time - start_time, "s","main time",mtime, "s")
`
`
frams 275 all time: 45.03623104095459 s main time 7.76613974571228 s
`

**Comment by aihacker111** [comment]
Make sure you adding provider and checking provider that onnx use is CPU or GPU, please install onnxruntime-gpu fit with cuda 11.x ỏ 12.x 
@juntaosun is use my model and run successfully on CUDA with boosting 3 time faster in my onnx model 

> Everything works fine, thanks to @aihacker111 for the contribution! ❤️❤️❤️ It's now very fast, at least 3 times faster than the original code on CUDA! 👍👍👍
> 
>  s7--s7_concat.mp4

**Comment by aihacker111** [comment]
@x4080 Yes it can run on apple silicon, but I’m just test on CPU M1 pro , you can try with MPS by adding CoreMLExecutionProvider in provider

**Comment by x4080** [comment]
@aihacker111 Cool, i just git yout repo then python inference_inference_onnx.py right ? It seems to download all .pth files ? I thought it only use onnx ?

And how to choose quantized vs non quantized version ?

Great work man

**Comment by aihacker111** [comment]
@x4080 I’m still in the clean code process, you can run on my repo for fun , I’ll update new code soon, the quantized of dynamic is better than static , but I have some issues with quantization that is slow down than original onnx and I’m still current fixing it, also I recommend you use original onnx model for better performance

**Comment by x4080** [comment]
@aihacker111 Cool, no probs man

**Comment by aihacker111** [comment]
@x4080 sometime , the speed is not only affect by the mode you use, it related to the code process and others reason, like I said yesterday , I’ll adding video summarization into it for reduce num frames and video size for fasting inference

**Comment by kitckso** [comment]
> @x4080 I’m still in the clean code process, you can run on my repo for fun , I’ll update new code soon, the quantized of dynamic is better than static , but I have some issues with quantization that is slow down than original onnx and I’m still current fixing it, also I recommend you use original onnx model for better performance

Do you mean the "3 times faster" is based on original ONNX model? And expect the quantized model will be faster after you fix?

**Comment by galigaligo** [comment]
> @x4080 sometime , the speed is not only affect by the model you use, it related to the code process and others reason, like I said yesterday , I’ll adding video summarization into it for reduce num frames and video size for fasting inference

Test onnx using live_portrait_onnx/onnx/:
Unified testing using s10.jpg and d8.mp4, with a total of 275 frames,
Test with 3060 graphics card and CUDA11.8
def initialized_models(self):
providers = ['CUDAExecutionProvider'] 
self.m_session = ort.InferenceSession(self.motion_extractor,  providers=providers)
self.f_session = ort.InferenceSession(self.features_extractor,  providers=providers)
self.w_session = ort.InferenceSession(self.warping,  providers=providers)
self.g_session = ort.InferenceSession(self.spade,  providers=providers)
self.s_session = ort.InferenceSession(self.stitch_path,  providers=providers)
self.s_l_session = ort.InferenceSession(self.lip_path,  providers=providers)
self.s_e_session = ort.InferenceSession(self.eye_path,  providers=providers)
The total time for the generate function is 153.2914435863495 seconds, while the warp code function takes 106.74874997138977 seconds
>PyTorch+CUDA, the total loop duration (including get-kpyinfo, stitching, parse_output, etc.) takes 45 seconds,

If only calculating the warming_madule and spade_generationor takes 7.76s
The speed is much slower than the original PyTorch version.
Is the speed improvement the live_portrait_onnx/quantification/quantification version?
I use live_portrait_onnx/quantification/dynamics, which is very slow,
Unable to generate images properly using live_portrait_onnx/quantification/static.

Speed: frams 275 generate function: 133.769793510437 s warp code function 115.6993567466736 s

https://github.com/user-attachments/assets/285aca2f-402e-45fd-8ef8-29c219346bc1

I don't know where the problem lies

**Comment by aihacker111** [comment]
@kitckso I’m not test quantization anymore, quantization converted like a options for everyone want to try, I don’t like quantization more because post-quantization maybe can make it faster but the performance not sure it good, I currently recommend everyone use original onnx

**Comment by aihacker111** [comment]
@galigaligo Please use non-quantization onnx model, controll onnx quantization is seem like hard , or you can wait the next plan of mine: TensorRT after I completed on onnx task

**Comment by galigaligo** [comment]
> 一切正常，感谢您的贡献！❤️❤️❤️ 它现在非常快，至少比 CUDA 上的原始代码快 3 倍！👍👍👍
> 
>  s7--s7_concat.mp4

我测试速度反而更慢了，
我的显卡是3060，CUDA 11.8，onnxruntime版本如下：
onnx                      1.16.1
onnxruntime               1.17.0
onnxruntime-gpu           1.17.0

**Comment by aihacker111** [comment]
@juntaosun Please help me to support them in CUDA onnx, i don’t have the computer right now 😅

**Comment by x4080** [comment]
I tested using kaggle, it seems not using CUDA for some reason

<img width="1315" alt="Screenshot 2024-07-13 at 10 38 43" src="https://github.com/user-attachments/assets/7b69f47a-9a7e-4f60-97c6-77fa5292f7ee">

**Comment by aihacker111** [comment]
@x4080 Kaggle is use cuda 12.7 , you need to check in their document 
https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html

**Comment by x4080** [comment]
@aihacker111 , even if available providers is correct ?

**Comment by aihacker111** [comment]
😂 make sure this document is require correct , onnxrumtime gpu is alway the hard option to fix and run 
Because the first idea of their is optimized on CPU 😂😂😂 
I’ll convert to tensorRT soon

**Comment by x4080** [comment]
@aihacker111 Thanks, no probs just curious why its not working, cheers

**Comment by MarsEverythingTech** [comment]
Hello,

Will the ONNX feature be implemented into the main repo anytime? 

Thanks in advance

**Comment by aihacker111** [comment]
Hi sure, after i finished clean code , will pull request for project

**Comment by MarsEverythingTech** [comment]
> Hi sure, after i finished clean code , will pull request for project

Thank you very much. I appreciate your hard work! Will it be easy to set it up?

**Comment by aihacker111** [comment]
Yeah , i’ll group code and installation as easy for everyone can use

**Comment by kitckso** [comment]
@aihacker111 Can you share you idea about   your video summarization plan? Do you mean detect key frames from driving video?

**Comment by aihacker111** [comment]
Video summarization will power if we control pefectly the moment detection in this, as between 2 squence frame we can group 1 frame 
We have 500 frame and then through video sum we can have 250 frames or < 500 frames
Just stop as the idea, I’ll try later
Or the plan B is use Optical flow to present the movement in video 
@kitckso

**Comment by aihacker111** [comment]
As you can imagine more when we connecting Motion Director (pan left , right, zoom in, out) to get result as a marketing video with more affect as well as animal meme 🤣, 
Rightnow I need to enhance it better , all idea i said will have someone do that

**Comment by kitckso** [comment]
@aihacker111 It seems interesting and I'm thinking how it works.

1.
Add video summerization to detect key frames
Only process key frames
This should cause some frames not moving and maybe produce strange result, or may only works if video have many idle frames

2.
Add video summerization to detect key frames
Detect key points on key frames
Interpolate key points on other frames
Run spade and warp on all frames as usual
This seems won't improve performance since the most time consuming parts are spade and warp, but we can't skip it on non-keyframes.

3.
Similar to 1, but use frame interpolation like https://github.com/google-research/frame-interpolation to interpolate other frames, but I forgot the performance of frame interpolation, it could possible slower than spade and warp.

**Comment by aihacker111** [comment]
@kitckso yeah you think right , but we have many open source and idea, so we can create a own idea , just testing and know extractly what we want

**Comment by kitckso** [comment]
@aihacker111 You're right, there are millions of possibilities by combining 2 or more projects, it is interesting to explore different combinations.
Thanks for your contribution on ONNX and ideas.

**Comment by aihacker111** [comment]
@kitckso 
This is my personal project: https://huggingface.co/spaces/myn0908/S2I-Artwork-Sketch-to-Image-Diffusion
My model is train on large datasets with Lora, so the result is good , but I find that the image generate related to prompt , so I’m connect Super Generate prompt by T5-XXL to my project and it work perfectly, 
Overall, Nothing is impossible my friend. Thank you

**Comment by aihacker111** [comment]
#133 Everyone please follow this to get new repo for running

**Comment by warmshao** [comment]
> > > 一切正常，感谢您的贡献！❤️❤️❤️ 它现在非常快，至少比 CUDA 上的原始代码快 3 倍！👍👍👍
> > > s7--s7_concat.mp4
> > 
> > 
> > 我测试了下，3060显卡，CUDA11.8
> > ONNX+CUDA 测试275帧 154.56s
> > pytorch+CUDA 测试275帧  144.68s
> > 我的怎么更慢了呢....
> 
> I'm using 3060 too. I haven't try ONNX, but I tested 2xx frames with pytorch only takes 18s, seems your speed is abnormal.

really, ~70ms/frame, how to do ?

**Comment by kitckso** [comment]
@warmshao Sorry that it's not accurate, it is the time for "animating" process, i.e. spade and warp. My video is 9s, fps is roughly 25, so frame number should be 2xx, I remember the whole process is around 30s. Roughly 3s to process 1s video.

I tested in Linux docker container.
Maybe CPU is also a factor, I found one CPU core is 100% loading.

**Comment by Echolink50** [comment]
> @warmshao Sorry that it's not accurate, it is the time for "animating" process, i.e. spade and warp. My video is 9s, fps is roughly 25, so frame number should be 2xx, I remember the whole process is around 30s. Roughly 3s to process 1s video.
> 
> I tested in Linux docker container. Maybe CPU is also a factor, I found one CPU core is 100% loading.

I also get a about 3 seconds to process each 1 second of video.

**Comment by MarsEverythingTech** [comment]
Hello, 

Is the ONNX feature integrated into GPU and uses CUDA?

Thanks

**Comment by aihacker111** [comment]
@MarsEverythingTech not yet, in fixing progress, wait some day Thank you

**Comment by aihacker111** [comment]
@juntaosun Hello, please share me some exp in convert with not downgrade pytorch version

**Comment by aihacker111** [comment]
ONNX feature updated and next plan in the next week right here: #142

**Comment by warmshao** [comment]
Both TensorRT and ONNXRUNTIME-GPU have been implemented in my repository https://github.com/warmshao/FasterLivePortrait. Both have improved speed, especially TensorRT which can achieve real-time rendering a frame at 30+ FPS. Feel free to enjoy it!

**Comment by chrisbward** [comment]
thanks @aihacker111 and @warmshao - any details on how we can replicate the onnx models, converting from the original files?

**Comment by warmshao** [comment]
> thanks @aihacker111 and @warmshao - any details on how we can replicate the onnx models, converting from the original files?

my script to export onnx: https://github.com/warmshao/LivePortrait/blob/multi_faces/export_onnx.py

**Comment by JimLee4530** [comment]
> > thanks @aihacker111 and @warmshao - any details on how we can replicate the onnx models, converting from the original files?
> 
> my script to export onnx: https://github.com/warmshao/LivePortrait/blob/multi_faces/export_onnx.py

i use your script to export onnx, but raise error 
"""
torch.onnx.errors.OnnxExporterError: Unsupported: ONNX export of operator GridSample with 5D volumetric input. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues
"""
Can you give me the environment configuration or some advers?

**Comment by aihacker111** [comment]
@JimLee4530 Upgrade your pytorch version with nightly preview 
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121

Then you change the opset version from 16 to 20

**Comment by JimLee4530** [comment]
> > > > thanks @aihacker111 and @warmshao - any details on how we can replicate the onnx models, converting from the original files?
> > > 
> > > 
> > > my script to export onnx: https://github.com/warmshao/LivePortrait/blob/multi_faces/export_onnx.py
> > 
> > 
> > i use your script to export onnx, but raise error """ torch.onnx.errors.OnnxExporterError: Unsupported: ONNX export of operator GridSample with 5D volumetric input. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues """ Can you give me the environment configuration ?
> 
> pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121 ![1721308680613](https://private-user-images.githubusercontent.com/138360003/349973734-aaff9caa-7a60-479c-b1cd-49bbb20ed86c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTc3MzAsIm5iZiI6MTcyMTM1NzQzMCwicGF0aCI6Ii8xMzgzNjAwMDMvMzQ5OTczNzM0LWFhZmY5Y2FhLTdhNjAtNDc5Yy1iMWNkLTQ5YmJiMjBlZDg2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwMjUwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmMzNGEzMTNkNDQ2YTgwZDAxODM4YjVhMTk3Y2I2NjkwODM1MjdkYzc5ZDE5ZTA3NTM0NTA4N2IyMDBmODcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zRifa24XJNYMBAOwnIdM-LxoJ5QYp_MTH4ipq108wPU)

thank you very much @warmshao @aihacker111 
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121

And change the opset version from 16 to 20 is work!

**Comment by warmshao** [comment]
Install-free, extract-and-play Windows package with TensorRT support now available!  please refer [FasterLivePortrait](https://github.com/warmshao/FasterLivePortrait) change logs, really convenient and very fast!!!

**Comment by ChunChenLin** [comment]
> This is the link to HuggingFace model id and Github code demo for running project with onnx model which I convert completed 5 original models
> 
> <img alt="Screenshot 2024-07-12 at 19 03 10" width="367" src="https://private-user-images.githubusercontent.com/159988742/348254833-75de87b9-975a-4711-8f18-f94cea0c6e97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDcwMjAsIm5iZiI6MTcyMjg0NjcyMCwicGF0aCI6Ii8xNTk5ODg3NDIvMzQ4MjU0ODMzLTc1ZGU4N2I5LTk3NWEtNDcxMS04ZjE4LWY5NGNlYTBjNmU5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQwODMyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWEyZTlkZTAzZDU3ZTdkNjcxNGI0Mjg4MWE2NjAwNWZmZGUzYjEzMTMzMTNhZTQ0NDJkNjk5NjI0MzdiZDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.usTgzX8N218pUjYbnTYtnv0qgEExyE9JdUmVj6oeLDM">
> I fixed the Grid Sample 5D error and successfully converted the Warping model via ONNX. Besides, other models all work fine and fast
> 
> Live Portrait ONNX: https://huggingface.co/myn0908/Live-Portrait-ONNX Github repo for running my ONNX: https://github.com/aihacker111/Efficient-Live-Portrait
> 
> Thank you @cleardusk and your team for great project

@aihacker111  May I ask how did you fix GridSample issue in warping module? Currently, I encounter the below error during the inference with ONNX model. Many thanks. :))

`onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from models/warping_module.onnx failed:Node (/dense_motion_network/GridSample) Op (GridSample) [ShapeInferenceError] Input 0 expected to have rank 4 but has rank 5`

**Comment by ZhiqiJiang** [comment]
> Oh for the explain of the question: Why the latest pytorch and onnx version is raising Grid Sample 5D model, I'm checking the function convert in ONNX and seem like it's a bug of Microsoft, it's block when the Convolution pass to the Converting Function -> this is a reason that cannot converted, but in the lower version Pytorch (example: Torch 1.13.0) Torch and ONNX lib is matching everything , seem like we have to back door

你好，torch==1.13.0 把模型从pytorch转成onnx时会报上面的错误，你遇到过吗？怎么解决的？

**Comment by jules-ai** [comment]
> [@aihacker111](https://github.com/aihacker111) May I ask how did you fix GridSample issue in warping module? Currently, I encounter the below error during the inference with ONNX model. Many thanks. :))
> 
> `onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from models/warping_module.onnx failed:Node (/dense_motion_network/GridSample) Op (GridSample) [ShapeInferenceError] Input 0 expected to have rank 4 but has rank 5`

I’m experiencing the same issue, and I think that it hasn’t been resolved at all. The conversion script in the project, [portrait2onnx_warping_models.py](https://github.com/aihacker111/Efficient-Live-Portrait/blob/main/experiment_examples/portrait2onnx/portrait2onnx_warping_models.py), even references a library called Face2Vid, which doesn’t seem to exist anywhere online. Because of this, no one can actually get the code to run. @aihacker111 Could you still find your conversion code ?
