### ISSUE TITLE
Started watching the repo please a gradio demo

### ISSUE THREAD

**Issue by FurkanGozukara** [KwaiVGI/LivePortrait#13]
that input image + input video (both auto cropped and processed) and generates output video

ty

**Comment by cleardusk** [comment]
Stay tuned, please!

**Comment by Inferencer** [comment]
it already has a gradio ui

**Comment by FurkanGozukara** [comment]
it is completed ty all

https://github.com/KwaiVGI/LivePortrait/issues/78
