### ISSUE TITLE
Can it be deployed and run on Windows?

### ISSUE THREAD

**Issue by githubnameoo** [KwaiVGI/LivePortrait#130]

**Comment by FurkanGozukara** [comment]
yes of course

# Windows LivePortrait Tutorial

**https://youtu.be/FPtpNrmuwXk**

### [**Animate Static Photos into Talking Videos with LivePortrait AI Compose Perfect Expressions Fast**](https://youtu.be/FPtpNrmuwXk)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/beNzm6ITK_5AnipzYt40Y.png)](https://youtu.be/FPtpNrmuwXk)

**Comment by zzzweakman** [comment]
Thank you for your interest. LivePortrait is compatible with Linux, Windows, and Mac. @githubnameoo

**Comment by zzzweakman** [comment]
Hi @githubnameoo, if you're having trouble managing the dependencies, we now offer a one-click installation package for Windows (install free). Please refer to our update from 7/25 for more details.
