### ISSUE TITLE
Paste-back not working as intended with --no_flag_stitching

### ISSUE THREAD

**Issue by Lesteriax** [KwaiVGI/LivePortrait#134]
I might have understood this wrong but when all 4 options are selected:

using flag:  --no_flag_stitching
relative motion = true
do crop (source)  = true
paste-back  = true
do crop (driving video)  = true

The results are still cropped even though the expected behavior is to paste back on the original. However, using the same 4 options without using the flag, it pastes back the results correctly.

So either paste-back is not working as intended with the stitching flag, or the 'do crop (source) is not working as intended without using the  --no_flag_stitching

**Comment by cleardusk** [comment]
In a sense, stitching is designed for pasting back. If cropping(source) is disabled, pasting back is meaningless. @Lesteriax 

https://github.com/KwaiVGI/LivePortrait/blob/b370d8059c4794ad2afce2db404e2aa5450e098c/src/live_portrait_pipeline.py#L210-L213
