### ISSUE TITLE
Hardware requirements 

### ISSUE THREAD

**Issue by abdurahmanshiine** [KwaiVGI/LivePortrait#136]
Hi there,

What are the hardware requirements to run this on a local machine?

**Comment by AlonDan** [comment]
I'm not sure but I can share my personal experience which is 10 years old PC with:
- Intel i7-4770K CPU @ 3.50GHz 
- Nvidia GTX 980 4GB VRAM
- 32GB RAM
- SSD
- Windows 10

I don't think any user have tested on such an antique machine, so I'm a good test subject to REALLY push the limits here, and IT WORKS!

---

So far I never got any "**out of memory**" message and it complete the task, even for 30-60 seconds long videos! it's just take AGES to process... 

Obviously it is MUCH slower with my current PC for testing, so I can't recommend using such a limited hardware.
And I'm not sure what are the limits unless the official developers will share this information.

**Comment by Lytanshade** [comment]
i see around 6GB VRAM and ~14GB RAM used. with chrome tabs and potplayer etc open. 
8GB VRAM and 32GB RAM would be ideal

**Comment by abdurahmanshiine** [comment]
@AlonDan @Lytanshade thank you very much both of you, this really helps 🙏

**Comment by FurkanGozukara** [comment]
Lesser than 4gb vram with half precision

**Comment by kitckso** [comment]
It use 5 tiny models, the largest one is just 55M parameters, input image size is 256x256. The current code is not optimized, it loads all models and all frames into memory. It should be possible to optimize memory usage by loading models on demand, and load 1 frame at a time, so I think it should almost fit in any hardware.

**Comment by shivshankar11** [comment]
> I'm not sure but I can share my personal experience which is 10 years old PC with:
> 
> * Intel i7-4770K CPU @ 3.50GHz
> * Nvidia GTX 980 4GB VRAM
> * 32GB RAM
> * SSD
> * Windows 10
> 
> I don't think any user have tested on such an antique machine, so I'm a good test subject to REALLY push the limits here, and IT WORKS!
> 
> So far I never got any "**out of memory**" message and it complete the task, even for 30-60 seconds long videos! it's just take AGES to process...
> 
> Obviously it is MUCH slower with my current PC for testing, so I can't recommend using such a limited hardware. And I'm not sure what are the limits unless the official developers will share this information.

I am running intel 2700k and 4090.
