### ISSUE TITLE
Errors when trying to launch app.py

### ISSUE THREAD

**Issue by darkguset** [KwaiVGI/LivePortrait#140]
I am on Linux Mint, i installed miniconda3 as the environment, passed all the installations without any errors, but when I try to launch app.py with Python I get the following errors:
![image](https://github.com/user-attachments/assets/f157c290-309a-4cbc-9d76-fa96af56fa8f)

**Comment by zzzweakman** [comment]
Thank you for your attention! Could you confirm that all the weights are placed in the correct location and that their sizes match those indicated in the [table](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#5-inference-speed-evaluation-) in the readme? @darkguset

**Comment by darkguset** [comment]
Aha! You are right, all the models exist but they are 134 bytes small! I used the git clone method to get them, but perhaps I should had downloaded them manually instead. I will download the models from Google drive, try again and let you know if it worked.

**Comment by cleardusk** [comment]
@darkguset Maybe you should `git lfs install` first, then `git clone https://huggingface.co/KwaiVGI/liveportrait pretrained_weights`

**Comment by darkguset** [comment]
I downloaded the weights and placed them manually - there is definitely progress but now I see a different error:
![image](https://github.com/user-attachments/assets/b87b62ab-7d65-4d08-ae90-7209d91d93a8)

**Comment by zzzweakman** [comment]
It seems there might be an issue with your CUDA installation. Could you please verify that both CUDA and cuDNN are correctly installed on your system? Typically, `libnvrtc.so` is included with the CUDA toolkit. @darkguset

**Comment by darkguset** [comment]
> It seems there might be an issue with your CUDA installation. Could you please verify that both CUDA and cuDNN are correctly installed on your system? Typically, `libnvrtc.so` is included with the CUDA toolkit. @darkguset

You were right. I thought I had installed it earlier but I think I somehow missed it. I installed CUDA and cuDNN and it seems to work now!

Many thanks guys! You can close this ticket (or If I am supposed to do that I will).
