### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mogun91** [KwaiVGI/LivePortrait#145]
Hello, I am a beginner user of Comfy UI. I installed it by following the video or content, but an error occurred. Please help me with the detailed solution. I feel like there is no node data, but I don't know what to do.
![001](https://github.com/user-attachments/assets/aa5a575d-7ae1-4aec-828c-173a8ab631f5)
![002](https://github.com/user-attachments/assets/dd207718-9e2a-4019-a4ce-586bc7d3a889)
![003](https://github.com/user-attachments/assets/dc8ef537-475d-4f16-b145-137c8a3c90a8)

**Comment by Lytanshade** [comment]
wrong repo.   You're after this one: https://github.com/kijai/ComfyUI-LivePortraitKJ

**Comment by westNeighbor** [comment]
check the messages in the terminal, it tells what fails you. Probably requirements.txt stuffs.

**Comment by FurkanGozukara** [comment]
if you can't make it work i have easier to follow tutorial

https://youtu.be/FPtpNrmuwXk

### [**Animate Static Photos into Talking Videos with LivePortrait AI Compose Perfect Expressions Fast**](https://youtu.be/FPtpNrmuwXk)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/beNzm6ITK_5AnipzYt40Y.png)](https://youtu.be/FPtpNrmuwXk)

**Comment by zzzweakman** [comment]
Thank you for your interest in LivePortrait. This repository does not provide Comfy UI functionality. Please consult the repository you are using for further assistance :) @mogun91
