### ISSUE TITLE
Customize temporary directory?

### ISSUE THREAD

**Issue by samsonsite1** [KwaiVGI/LivePortrait#147]
I would like to customize the temporary directory so all scratch files are written there instead of
AppData\Local\Temp\gradio\1234

Is that possible? (running on Windows)
Thanks.

**Comment by zzzweakman** [comment]
> I would like to customize the temporary directory so all scratch files are written there instead of AppData\Local\Temp\gradio\1234
> 
> Is that possible? (running on Windows) Thanks.

Hi @samsonsite1, yes, it's possible! You can now customize the temporary directory by using the new [parameter](https://github.com/KwaiVGI/LivePortrait/blob/main/src/config/argument_config.py#L54) we've added. Just pull the latest updates : )
