### ISSUE TITLE
ModuleNotFoundError: No module named 'tyro'

### ISSUE THREAD

**Issue by kamran7272** [KwaiVGI/LivePortrait#151]
when i use  python app.py i get this error

Traceback (most recent call last):
  File "E:\S2\s22\LivePortrait\app.py", line 7, in <module>
    import tyro
ModuleNotFoundError: No module named 'tyro'

**Comment by samsonsite1** [comment]
pip install tyro==0.8.5

**Comment by cleardusk** [comment]
@kamran7272 https://github.com/KwaiVGI/LivePortrait/blob/54e50986b232fc3f382f20924cdff675c0ce729d/requirements.txt#L21  Thanks for @samsonsite1 's reply 💖
