### ISSUE TITLE
Issues Launching "python app.py" - Windows 10

### ISSUE THREAD

**Issue by LukeCarmona** [KwaiVGI/LivePortrait#153]
>python app.py
Traceback (most recent call last):
  File "C:\Users\-\Desktop\LivePortrait\LivePortrait\app.py", line 11, in <module>
    from src.utils.helper import load_description
  File "C:\Users\-\Desktop\LivePortrait\LivePortrait\src\utils\helper.py", line 9, in <module>
    import torch
  File "C:\Users\-\AppData\Roaming\Python\Python310\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\-\AppData\Roaming\Python\Python310\site-packages\torch\lib\shm.dll" or one of its dependencies.

**Comment by FurkanGozukara** [comment]
if i were you i would do this

uninstall existing python

install as shown here into c drive along with cuda, ffmpeg and c++ tools : https://youtu.be/-NjNy7afOQ0

then reinstall live portrait into your C drive and it should fix your problem

also i have 1-click installer and tutorial for live portrait here : https://youtu.be/FPtpNrmuwXk

**Comment by zzzweakman** [comment]
> > python app.py
> > Traceback (most recent call last):
> > File "C:\Users-\Desktop\LivePortrait\LivePortrait\app.py", line 11, in 
> > from src.utils.helper import load_description
> > File "C:\Users-\Desktop\LivePortrait\LivePortrait\src\utils\helper.py", line 9, in 
> > import torch
> > File "C:\Users-\AppData\Roaming\Python\Python310\site-packages\torch__init__.py", line 141, in 
> > raise err
> > OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users-\AppData\Roaming\Python\Python310\site-packages\torch\lib\shm.dll" or one of its dependencies.

Hi @LukeCarmona, it looks like your PyTorch installation is not set up correctly. If you're having trouble managing the dependencies, we now offer a one-click installation package for Windows (install free). Please refer to our update from 7/25 for more details.

**Comment by zzzweakman** [comment]
@LukeCarmona Windows users can now download the package from [HuggingFace](https://huggingface.co/cleardusk/LivePortrait-Windows/tree/main) or [BaiduYun](https://pan.baidu.com/s/1FWsWqKe0eNfXrwjEhhCqlw?pwd=86q2). More details can be found [here](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#-updates).
