### ISSUE TITLE
 If there are any plans to open-source the vid2vid project? 

### ISSUE THREAD

**Issue by ZerRui** [KwaiVGI/LivePortrait#159]
Thank you for your outstanding work, and kudos to your team! Having viewed your project webpage, I am thoroughly impressed with the vid2vid results. I am curious to know if there are any plans to open-source the vid2vid project? I eagerly await your response. Once again, my sincere gratitude to you and your team for your remarkable contributions!

**Comment by zzzweakman** [comment]
blendedThank you for your attention! The vid2vid feature is currently under development. 😊 We will also support it in the Gradio demo. Stay tuned! @ZerRui
