### ISSUE TITLE
Help With Latest Update

### ISSUE THREAD

**Issue by MarsEverythingTech** [KwaiVGI/LivePortrait#162]
Hello,

Recently, the repo has been updated, and when I git pull, I have 3 requirements.txt files. I am using Windows 11, which file do I use to pip install -r after git pull, the requirements.txt or requirements_base.txt?

Thanks in advance

**Comment by cleardusk** [comment]
`requirements.txt `

```
# install dependencies with pip (for Linux and Windows)
pip install -r requirements.txt
```

**Comment by MarsEverythingTech** [comment]
> `requirements.txt `
> 
> ```
> # install dependencies with pip (for Linux and Windows)
> pip install -r requirements.txt
> ```

Oh thanks. By the way, what does the requirements_base.txt do?

**Comment by Inferencer** [comment]
Base.txt is the normal requirements they have set this up so users can install the windows/Linux version via requirements.txt which will install something related to those systems then proceed with the normal requirements (base.txt)

Macos users have an option to install via the macos requirements.txt that will install something related to macos then proceed with the normal requirements (base.txt)

**Comment by MarsEverythingTech** [comment]
> Base.txt is the normal requirements they have set this up so users can install the windows/Linux version via requirements.txt which will install something related to those systems then proceed with the normal requirements (base.txt)
> 
> Macos users have an option to install via the macos requirements.txt that will install something related to macos then proceed with the normal requirements (base.txt)

Okay, so whenever I git pull, I do pip install -r requirements.txt when that file is updated?

**Comment by Inferencer** [comment]
> > Base.txt is the normal requirements they have set this up so users can install the windows/Linux version via requirements.txt which will install something related to those systems then proceed with the normal requirements (base.txt)
> > Macos users have an option to install via the macos requirements.txt that will install something related to macos then proceed with the normal requirements (base.txt)
> 
> Okay, so whenever I git pull, I do pip install -r requirements.txt when that file is updated?

yeah

**Comment by zzzweakman** [comment]
> > Base.txt is the normal requirements they have set this up so users can install the windows/Linux version via requirements.txt which will install something related to those systems then proceed with the normal requirements (base.txt)
> > Macos users have an option to install via the macos requirements.txt that will install something related to macos then proceed with the normal requirements (base.txt)
> 
> Okay, so whenever I git pull, I do pip install -r requirements.txt when that file is updated?

If you are using Windows, you don't need to install any new dependencies for our latest update. @MarsEverythingTech

Thank you for your warm heart and quick replies to so many users 💗. @Inferencer

**Comment by MarsEverythingTech** [comment]
> > > Base.txt is the normal requirements they have set this up so users can install the windows/Linux version via requirements.txt which will install something related to those systems then proceed with the normal requirements (base.txt)
> > > Macos users have an option to install via the macos requirements.txt that will install something related to macos then proceed with the normal requirements (base.txt)
> > 
> > 
> > Okay, so whenever I git pull, I do pip install -r requirements.txt when that file is updated?
> 
> If you are using Windows, you don't need to install any new dependencies for our latest update. @MarsEverythingTech
> 
> Thank you for your warm heart and quick replies to so many users 💗. @Inferencer

Hello, recently your repo has been updated with vid2vid. I think I need to pip install -r requirements_base,txt right? Since it has new package for the new update to work. 

Thanks in advance

**Comment by zzzweakman** [comment]
> Hello, recently your repo has been updated with vid2vid. I think I need to pip install -r requirements_base,txt right? Since it has new package for the new update to work.
> 
> Thanks in advance

Yes, you can update the base dependencies by running: `pip install -r requirements_base.txt`. Alternatively, you can install the only new dependency with: `pip install pykalman==0.9.7`.
