### ISSUE TITLE
Have plan to support anime or animal?

### ISSUE THREAD

**Issue by troycjj** [KwaiVGI/LivePortrait#167]
Have plan to support anime or animal?
very thanks

**Comment by handles98** [comment]
same

**Comment by tomakorea** [comment]
There are already animals in the demos (finetunes) but it's not available to download. For anime, it works already but the when eyes are closed it's a bit off, same for the mouth that is far from perfect compared to more realistic styles.

**Comment by zzzweakman** [comment]
> Have plan to support anime or animal? very thanks

LivePortrait already supports processing animated images to some extent. The animal feature is already available. You can check it out [here](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#-updates).

**Comment by gordon0414** [comment]
@zzzweakman anime needs to be fine-tuned IMO. it works, but not good as human or animals
