### ISSUE TITLE
v2v error: More than one face detected in the source frame

### ISSUE THREAD

**Issue by justcoding88** [KwaiVGI/LivePortrait#175]
If the source image has more than one face, we see this in the console: "More than one face detected in the image, only pick one face by rule large-small.". This works correctly.

However, using the new video-to-video, if the source video has more than one face, instead if picking one face, we get an error and it crashes:

```  
File "E:\git\LivePortrait\src\gradio_pipeline.py", line 90, in execute_video
  video_path, video_path_concat = self.execute(self.args)
File "E:\git\LivePortrait\src\live_portrait_pipeline.py", line 182, in execute
  ret_s = self.cropper.crop_source_video(source_rgb_lst, crop_cfg)
File "E:\git\LivePortrait\src\utils\cropper.py", line 135, in crop_source_video
  log(f"More than one face detected in the source frame_{idx}, only pick one face by rule {direction}.")
```

In my test, the source image worked on a screenshot from the video which did not work.

**Comment by justcoding88** [comment]
As a workaround, I added this line to cropped.py line 135: `direction="large-small"`

So, line 134-136 now looks like this, and it works:
```
elif len(src_face) > 1:
    direction="large-small"
    log(f"More than one face detected in the source frame_{idx}, only pick one face by rule {direction}.")
```

(I realize for this purpose it may not matter what "direction" is actually set to, I just used this value since it seemed consistent with what is used elsewhere)

**Comment by cleardusk** [comment]
Thanks for your feedback! It is fixed now https://github.com/KwaiVGI/LivePortrait/issues/175
