### ISSUE TITLE
Amazing work

### ISSUE THREAD

**Issue by nitinmukesh** [KwaiVGI/LivePortrait#18]
It really worked. No post processing required. Loved it.

Thanks to all

[Jianzhu Guo](https://github.com/cleardusk) 1†   [Dingyun Zhang](https://github.com/KwaiVGI) 1,2   [Xiaoqiang Liu](https://github.com/KwaiVGI) 1   [Zhizhou Zhong](https://github.com/KwaiVGI) 1,3   [Yuan Zhang](https://scholar.google.com.hk/citations?user=_8k1ubAAAAAJ) 1 
[Pengfei Wan](https://scholar.google.com/citations?user=P6MraaYAAAAJ) 1   [Di Zhang](https://openreview.net/profile?id=~Di_ZHANG3) 1

Would love to see the audio from reference video is stitched in output video

**Comment by zzzweakman** [comment]
> It really worked. No post processing required. Loved it.
> 
> Thanks to all
> 
> [Jianzhu Guo](https://github.com/cleardusk) 1†   [Dingyun Zhang](https://github.com/KwaiVGI) 1,2   [Xiaoqiang Liu](https://github.com/KwaiVGI) 1   [Zhizhou Zhong](https://github.com/KwaiVGI) 1,3   [Yuan Zhang](https://scholar.google.com.hk/citations?user=_8k1ubAAAAAJ) 1  [Pengfei Wan](https://scholar.google.com/citations?user=P6MraaYAAAAJ) 1   [Di Zhang](https://openreview.net/profile?id=~Di_ZHANG3) 1
> 
> Would love to see the audio from reference video is stitched in output video

Thank you so much for your positive feedback! we are happy to inform you that LivePortrait now supports generating videos with audio. For more details, please check out the [updates](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#-updates).
