### ISSUE TITLE
vid-to-vid_cut off

### ISSUE THREAD

**Issue by buddylee7** [KwaiVGI/LivePortrait#182]
When using a driving video to animate the target video it seems to cut the driving video off.  The attached example is supposed to say nice but is cut off.

https://github.com/user-attachments/assets/8ff49af0-b76c-42af-920c-38d7529c9ac7

**Comment by kashishnaqvi101** [comment]
Hey, how did you generate this result? 
I am always getting audio of source video and lip movements are mixed from both the source and driving video.

**Comment by cleardusk** [comment]
@buddylee7 Try to change the fps of nice.mp4 to 30

**Comment by fugueblus** [comment]
The frame number of the drive video and the source video are set to the same. The frame rate of the drive video determines the total number of frames in the video. For example, if the frame numbers of the drive video and the source video is set to 100 and the frame rate of the drive video is set to 25, the video length will be 4 seconds.
