### ISSUE TITLE
How to update to the newest version?

### ISSUE THREAD

**Issue by TomiTom1234** [KwaiVGI/LivePortrait#185]
It is not an issue, sorry.
I just don't know how to update to the newest version.
I have the gradio version installed, which is photo to video.
But what commands or steps should I do to update it to the last version, where also a video to video is included?
I will be very appreciated.

**Comment by FurkanGozukara** [comment]
you can do git pull and reinstall requirements

or install as you did first time into a new folder :)

**Comment by TomiTom1234** [comment]
> you can do git pull and reinstall requirements
> 
> or install as you did first time into a new folder :)

Thank you for your quick reply. But the problem is I am not really that skilled with these commands.
Can you kindly please explain how to do "git pull" exactly? What are the commands for that?
Much appreciate it.

**Comment by FurkanGozukara** [comment]
@TomiTom1234 git pull explained in this video : https://youtu.be/-NjNy7afOQ0

17:12 All about Git commands such as checkout, clone, pull, stash, pop
17:22 How to install Automatic1111 Stable Diffusion Web UI properly
17:46 How to open a CMD in that current drive directly
17:56 How to do a git clone to download the Automatic1111 Web UI or any GitHub repository
18:18 How to do a git checkout to switch different branches such as dev branch
18:38 Explanation of different branches in GitHub repository, example Automatic1111 repo
19:00 How to do git pull to update and verify latest version of a repo

if you are total noob you can use my 1-click installer which has the very latest version + extra feature 

1-click install tutorial : https://youtu.be/FPtpNrmuwXk

![Live_Portrait_SECourses_APP](https://github.com/user-attachments/assets/1fa26460-cc83-4ee6-81b8-d32bed6c4460)

**Comment by TomiTom1234** [comment]
Thank you!
I got it updated with git pull, much love! ❤️
