### ISSUE TITLE
How to keep the source video with a still head？ 

### ISSUE THREAD

**Issue by HonglinChu** [KwaiVGI/LivePortrait#188]
Hi，i meet two problem:
（1）When the driving video's head keep still，the head of source video always has slight shake, how to avoid it?
（2）Sometimes，the head of driving video suddenly enlarges or shrinks even though the head of  driving video remains still( Note that the face id in  both source image and driving video is same).

**Comment by Mystery099** [comment]
Thanks for your feedback.

(1) If you feel the animated video has some jitter, please adjust the `driving_smooth_observation_variance` parameter in `src/config/argument_config.py`. We recommend that you change it by a factor of 10. For example, if the current value is 3e-7 and you feel the animated result is a bit jittery, you can adjust it to 3e-6, and so on. If you are using `app.py`, the corresponding adjustment location is `motion smooth strength (v2v)`.

(2) The problem you mentioned that the face sometimes looks scaled in the animated results is a known issue. If the head is still in your driving video, you can try to alleviate it by ensuring that there is no obvious jump in expression between driving video frames.

**Comment by HonglinChu** [comment]
Thank you！

**Comment by FurkanGozukara** [comment]
@Mystery099 thank you so much

Do you have explanation somewhere for other parameters as well?

**Comment by Mystery099** [comment]
Thank you for your feedback. @FurkanGozukara 

Currently, you can refer to the parameter comments in `src/config/argument_config.py`. The new parameters related to v2v are: `flag_source_video_eye_retargeting`, `flag_video_editing_head_rotation`, and `driving_smooth_observation_variance`. If you are using app.py, the corresponding options of the latter two are `relative head rotation (v2v)` and `motion smooth strength (v2v)`.

We will make a tutorial later, such as a video tutorial.

**Comment by FurkanGozukara** [comment]
@Mystery099 thanks a lot
