### ISSUE TITLE
New Feature Face-ID Adapter for Control Face animation in the Multiple Faces image is availabled 🔥🔥🔥🔥🔥

### ISSUE THREAD

**Issue by aihacker111** [KwaiVGI/LivePortrait#194]
# Check List:
+ This new update is using Face-ID AcrFace to control Face Animations in the Multiples Images 
+ I'm also update new TensorRT run on latest TensorRT version
+ Project can run on Google Colab for demo, I'll update Gradio Interface later 

+ In many near day ago, I'm assigned to the new research paper, so I cannot update new feature faster, but now the model is came to the training process, so I come back to update new idea on this great project 
Thank you and see result using Face-ID Adapter in Live-Portrait

+ Checkout here for run demo: https://github.com/aihacker111/Efficient-Live-Portrait

# REFINE IMAGE: 
![368220873_826368889022136_4472311944594836999_n](https://github.com/user-attachments/assets/e1dfd5d1-12d3-4a3a-bf7e-cfd2125fe3eb)
# Result Video control Face-Animation

https://github.com/user-attachments/assets/bc47d894-a984-4bce-8851-4921b40c7480

**Comment by FurkanGozukara** [comment]
so this is just for picking certain face in the given image right? 

i plan to add something simpler to my scripts if authors not planning

face index to change both in source images and videos

**Comment by Yoshi-des** [comment]
Hoho good job bro. I'm proud of you 🤩🤩🥳

**Comment by aihacker111** [comment]
@FurkanGozukara Dear sir, check out this Multiples Index Face Motion 

https://github.com/user-attachments/assets/ea77a9af-9e3a-4537-8011-eb781dad9b62



https://github.com/user-attachments/assets/474be89a-51e7-4474-8fd4-6fed089f0b6c
