### ISSUE TITLE
--driving_smooth_observation_variance 请问为何没找到这个参数呢 谢谢

### ISSUE THREAD

**Issue by tutuaio** [KwaiVGI/LivePortrait#198]
~/LivePortrait$ python app.py --driving_smooth_observation_variance --flag_video_editing_head_rotation
╭─ Unrecognized options ─────────────────────────────────────────────────────────────────────────╮
│ Unrecognized options: --driving-smooth-observation-variance --flag-video-editing-head-rotation │
│ ───────────────────────────────────────────────────────────────────────────────────────

**Comment by tutuaio** [comment]
已解决。代码没拉下来...

**Comment by zzzweakman** [comment]
Thank you for your attention. If you have any other questions, please feel free to ask : ) @tutuaio
