### ISSUE TITLE
animals

### ISSUE THREAD

**Issue by Inferencer** [KwaiVGI/LivePortrait#20]
face detector not detecting animals such as dogs and cats although project pages mentions it might be possible

**Comment by xpeng** [comment]
same question

**Comment by kigner** [comment]
insightface cannot detect animal faces, only human faces

**Comment by zzzweakman** [comment]
You can refer to the appendix section D in our paper. To animate animals, the models should be fine-tuned on a small dataset of animal portraits combined with the original data.
