### ISSUE TITLE
mac 电脑能运行么？readme介绍时，只介绍安装python？各系统都支持了？

### ISSUE THREAD

**Issue by wming3** [KwaiVGI/LivePortrait#200]
mac、windows、linux  都能使用么？还是只能windows

**Comment by zzzweakman** [comment]
> mac、windows、linux 都能使用么？还是只能windows

It supports all three operating systems: Mac, Windows, and Linux. If you have any other questions, please feel free to ask!

**Comment by wming3** [comment]
cpu：Intel  not  install
