### ISSUE TITLE
Gradio interface  视频生成后，在浏览器中为加载出来

### ISSUE THREAD

**Issue by wming3** [KwaiVGI/LivePortrait#202]
mac系统
提示在 animations目录下生成了视频文件，在浏览器 http://127.0.0.1:8890/ 的 Step 3: 中没有加载，依然在计时
![image](https://github.com/user-attachments/assets/d8869c17-141a-42ae-9154-95e5faf4f162)
![image](https://github.com/user-attachments/assets/b909ee8e-8dc9-4d2e-bb4a-ea3a5fe2b179)

**Comment by FurkanGozukara** [comment]
restart browser next time should be fixed
happens sometimes

**Comment by zzzweakman** [comment]
当运行时间过长的时候，gradio似乎无法显示结果，我们自己本地测试的时候也有类似的现象。我们推荐在gradio上尽可能运行一些处理时间较短的样例，如果要处理长视频建议使用`inference.py`。

When the runtime is extensive, Gradio seems to have difficulty displaying results, a phenomenon we've also encountered during our local testing. We recommend running shorter examples on Gradio, and for processing longer videos, it's suggested to use `inference.py`.
@wming3
