### ISSUE TITLE
How to use video2template.py

### ISSUE THREAD

**Issue by MarsEverythingTech** [KwaiVGI/LivePortrait#21]
Hello, 

How can I use video2template to create a good driving video?

Thanks in advance.

**Comment by cleardusk** [comment]
Thanks for you attention. We are working on it, stay tuned!

**Comment by Yutong18** [comment]
Do I need to change config to animate reference photo with more than one portraits. Now only one face has been detected and animated. Thank you!

**Comment by zhaoyun0071** [comment]
> Hello, 
> 
> How can I use video2template to create a good driving video?
> 
> Thanks in advance.

那个不是制作驱动视频的，只是生成pkl的数据格式

**Comment by Mrkomiljon** [comment]
@cleardusk Hello bro, is it possible to use in real time ?

**Comment by cleardusk** [comment]
video2template.py lies in https://github.com/KwaiVGI/LivePortrait/blob/main/src/live_portrait_pipeline.py#L254-L285 now

**Comment by cleardusk** [comment]
@Mrkomiljon It requires more engineering work.
