### ISSUE TITLE
Cant load source video

### ISSUE THREAD

**Issue by TanvirHafiz** [KwaiVGI/LivePortrait#222]
THe huggingface repo says I can use a source video (not just a source image) if i run this in my computer in gradio interface. well i ran it in my computer in gradio but i dont seem to be able to upload a source video. it wont accept any video format. Am I doing something wrong? or is there any additional steps I need to take. Any one please help. thanks

**Comment by NeuralFalconYT** [comment]
## Download and Install the latest version of LivePortrait and select ```Source Video``` tab
![gradio](https://github.com/user-attachments/assets/f823d197-43b3-43c5-9b1d-cb66daaa01d2)

**Comment by zzzweakman** [comment]
> THe huggingface repo says I can use a source video (not just a source image) if i run this in my computer in gradio interface. well i ran it in my computer in gradio but i dont seem to be able to upload a source video. it wont accept any video format. Am I doing something wrong? or is there any additional steps I need to take. Any one please help. thanks

Thanks for your attention.  Now the v2v mode is only available in the GitHub version. The v2v mode heavily relies on landmark detection (ONNX backend). However, since HF Spaces do not support ONNX on GPU, it will perform very slowly in HF. @TanvirHafiz
