### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TechNova20** [KwaiVGI/LivePortrait#227]
I'm currently not getting straight face in my video for source, why does it not work when source video has a person talking?
Thanks for the help!

**Comment by FurkanGozukara** [comment]
Yes it is in the config file

I added that to my gradio after noticing it :)

**Comment by cleardusk** [comment]
@TechNova20 Change `source_max_dim `
https://github.com/KwaiVGI/LivePortrait/blob/cf74ed3c16f9d0448cece636109aa47ee29527b5/src/config/inference_config.py#L54
