### ISSUE TITLE
Driving image instead of driving video

### ISSUE THREAD

**Issue by killah-t-cell** [KwaiVGI/LivePortrait#229]
I wrote custom code to take in a driving image instead of video... it mostly works:

<img width="200" alt="Screenshot 2024-07-25 at 11 58 39 PM" src="https://github.com/user-attachments/assets/5e006d5b-85c6-4a30-82b8-40d6f26a4115">
<img width="200" alt="Screenshot 2024-07-25 at 11 58 29 PM" src="https://github.com/user-attachments/assets/168906f5-2ebc-4c18-9ba1-3800d757bb1c">
<img width="200" alt="Screenshot 2024-07-25 at 11 58 20 PM" src="https://github.com/user-attachments/assets/6ac8ab49-254e-46f2-923d-69c31d77b0c7">

but sometimes it suffers from poor restitching and facial deformation. 
<img width="200" alt="Screenshot 2024-07-26 at 12 01 03 AM" src="https://github.com/user-attachments/assets/0ea8e74a-4146-425c-b310-1fd15b2c445b">
<img width="200" alt="Screenshot 2024-07-26 at 12 01 35 AM" src="https://github.com/user-attachments/assets/b4e9fb21-6b63-49ec-badd-b7a34f328187">
<img width="200" alt="Screenshot 2024-07-26 at 12 01 19 AM" src="https://github.com/user-attachments/assets/7447e77e-17b2-4871-9b10-7aabc1e39aa9">

Here's my code

```
    def execute_face_transfer(self, args: ArgumentConfig):
        # for convenience
        inf_cfg = self.live_portrait_wrapper.inference_cfg
        crop_cfg = self.cropper.crop_cfg

        ######## load source input ########
        img_rgb = args.source  # Assuming args.source is already a numpy array
        img_rgb = resize_to_limit(img_rgb, inf_cfg.source_max_dim, inf_cfg.source_division)
        source_rgb_lst = [img_rgb]

        ######## process driving info ########
        driving_rgb = args.driving  # Assuming args.driving is already a numpy array
        driving_rgb = resize_to_limit(driving_rgb, inf_cfg.source_max_dim, inf_cfg.source_division)

        ######## prepare for pasteback ########
        flag_normalize_lip = inf_cfg.flag_normalize_lip
        lip_delta_before_animation = None

        ######## process source info ########
        if inf_cfg.flag_do_crop:
            crop_info = self.cropper.crop_source_image(source_rgb_lst[0], crop_cfg)
            if crop_info is None:
                raise Exception("No face detected in the source image!")
            source_lmk = crop_info['lmk_crop']
            img_crop_256x256 = crop_info['img_crop_256x256']
        else:
            source_lmk = self.cropper.calc_lmk_from_cropped_image(source_rgb_lst[0])
            img_crop_256x256 = cv2.resize(source_rgb_lst[0], (256, 256))

        I_s = self.live_portrait_wrapper.prepare_source(img_crop_256x256)
        x_s_info = self.live_portrait_wrapper.get_kp_info(I_s)
        x_c_s = x_s_info['kp']
        R_s = get_rotation_matrix(x_s_info['pitch'], x_s_info['yaw'], x_s_info['roll'])
        f_s = self.live_portrait_wrapper.extract_feature_3d(I_s)
        x_s = self.live_portrait_wrapper.transform_keypoint(x_s_info)

        if flag_normalize_lip and inf_cfg.flag_relative_motion and source_lmk is not None:
            c_d_lip_before_animation = [0.]
            combined_lip_ratio_tensor_before_animation = self.live_portrait_wrapper.calc_combined_lip_ratio(c_d_lip_before_animation, source_lmk)
            if combined_lip_ratio_tensor_before_animation[0][0] >= inf_cfg.lip_normalize_threshold:
                lip_delta_before_animation = self.live_portrait_wrapper.retarget_lip(x_s, combined_lip_ratio_tensor_before_animation)

        if inf_cfg.flag_pasteback and inf_cfg.flag_do_crop and inf_cfg.flag_stitching:
            mask_ori_float = prepare_paste_back(inf_cfg.mask_crop, crop_info['M_c2o'], dsize=(source_rgb_lst[0].shape[1], source_rgb_lst[0].shape[0]))

        ######## process driving info ########
        driving_crop_info = self.cropper.crop_source_image(driving_rgb, crop_cfg)
        if driving_crop_info is None:
            raise Exception("No face detected in the driving image!")
        driving_img_crop_256x256 = driving_crop_info['img_crop_256x256']
        
        I_d = self.live_portrait_wrapper.prepare_source(driving_img_crop_256x256)
        x_d_info = self.live_portrait_wrapper.get_kp_info(I_d)
        
        ######## animate (single frame) ########
        x_d_info = self.live_portrait_wrapper.get_kp_info(I_d)
        R_d = x_d_info['R'] if 'R' in x_d_info.keys() else get_rotation_matrix(x_d_info['pitch'], x_d_info['yaw'], x_d_info['roll'])

        if inf_cfg.flag_relative_motion:
            R_new = (R_d @ R_s.permute(0, 2, 1)) @ R_s
            delta_new = x_s_info['exp'] + (x_d_info['exp'] - x_s_info['exp'])
            scale_new = x_s_info['scale'] * (x_d_info['scale'] / x_s_info['scale'])
            t_new = x_s_info['t'] + (x_d_info['t'] - x_s_info['t'])
        else:
            R_new = R_d
            delta_new = x_d_info['exp']
            scale_new = x_s_info['scale']
            t_new = x_d_info['t']

        t_new[..., 2].fill_(0)  # zero tz
        x_d_i_new = scale_new * (x_c_s @ R_new + delta_new) + t_new

        # Algorithm 1:
        if not inf_cfg.flag_stitching and not inf_cfg.flag_eye_retargeting and not inf_cfg.flag_lip_retargeting:
            # without stitching or retargeting
            if flag_normalize_lip and lip_delta_before_animation is not None:
                x_d_i_new += lip_delta_before_animation
        elif inf_cfg.flag_stitching and not inf_cfg.flag_eye_retargeting and not inf_cfg.flag_lip_retargeting:
            # with stitching and without retargeting
            if flag_normalize_lip and lip_delta_before_animation is not None:
                x_d_i_new = self.live_portrait_wrapper.stitching(x_s, x_d_i_new) + lip_delta_before_animation
            else:
                x_d_i_new = self.live_portrait_wrapper.stitching(x_s, x_d_i_new)
        else:
            eyes_delta, lip_delta = None, None
            if inf_cfg.flag_eye_retargeting and source_lmk is not None:
                c_d_eyes = self.live_portrait_wrapper.calc_ratio([driving_crop_info['lmk_crop']])[0]
                combined_eye_ratio_tensor = self.live_portrait_wrapper.calc_combined_eye_ratio(c_d_eyes, source_lmk)
                eyes_delta = self.live_portrait_wrapper.retarget_eye(x_s, combined_eye_ratio_tensor)
            if inf_cfg.flag_lip_retargeting and source_lmk is not None:
                c_d_lip = self.live_portrait_wrapper.calc_ratio([driving_crop_info['lmk_crop']])[1]
                combined_lip_ratio_tensor = self.live_portrait_wrapper.calc_combined_lip_ratio(c_d_lip, source_lmk)
                lip_delta = self.live_portrait_wrapper.retarget_lip(x_s, combined_lip_ratio_tensor)

            if inf_cfg.flag_relative_motion:
                x_d_i_new = x_s + (eyes_delta if eyes_delta is not None else 0) + (lip_delta if lip_delta is not None else 0)
            else:
                x_d_i_new = x_d_i_new + (eyes_delta if eyes_delta is not None else 0) + (lip_delta if lip_delta is not None else 0)

            if inf_cfg.flag_stitching:
                x_d_i_new = self.live_portrait_wrapper.stitching(x_s, x_d_i_new)

        out = self.live_portrait_wrapper.warp_decode(f_s, x_s, x_d_i_new)
        I_p = self.live_portrait_wrapper.parse_output(out['out'])[0]

        # Convert BGR to RGB
        I_p_rgb = cv2.cvtColor(I_p, cv2.COLOR_BGR2RGB)
        source_rgb = cv2.cvtColor(source_rgb_lst[0], cv2.COLOR_BGR2RGB)

        if inf_cfg.flag_pasteback and inf_cfg.flag_do_crop and inf_cfg.flag_stitching:
            I_p_pstbk = paste_back(I_p_rgb, crop_info['M_c2o'], source_rgb, mask_ori_float)
            return I_p_pstbk
        else:
            return I_p_rgb
```

Is there anything I am doing wrong? Is the problem that my faces aren't always frontal? Plus, is there a way to manipulate more emotions through sliders – not only eyes and mouth? I noticed the "exp" is simply read from the driving video, and I figured it could be understandable as well!

**Comment by aihacker111** [comment]
@killah-t-cell seem like the keypoint is based on the original image and driving image you use, it's will control base on landmark of driving video and then paste-back to the original image, you can reverse 2 image, and compare 2 result

**Comment by YoungofNUAA** [comment]
> I wrote custom code to take in a driving image instead of video... it mostly works:
> 
> <img alt="Screenshot 2024-07-25 at 11 58 39 PM" width="200" src="https://private-user-images.githubusercontent.com/26853713/352424268-5e006d5b-85c6-4a30-82b8-40d6f26a4115.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDY5NzAsIm5iZiI6MTcyMjY0NjY3MCwicGF0aCI6Ii8yNjg1MzcxMy8zNTI0MjQyNjgtNWUwMDZkNWItODVjNi00YTMwLTgyYjgtNDBkNmYyNmE0MTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDAwNTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMTU4YzUxMTQ1YjY0ZGEzNzkyN2U2MjU5MjI2MTc5MmYxZDFhM2FkMDdhNmZhZWE4YTk3YWRlMzQ2OTVkMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lwe15Jvj9xQ4Qu8vx2zSJ43BGnCbdXxfa1zdIxJj7EE"> <img alt="Screenshot 2024-07-25 at 11 58 29 PM" width="200" src="https://private-user-images.githubusercontent.com/26853713/352424153-168906f5-2ebc-4c18-9ba1-3800d757bb1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDY5NzAsIm5iZiI6MTcyMjY0NjY3MCwicGF0aCI6Ii8yNjg1MzcxMy8zNTI0MjQxNTMtMTY4OTA2ZjUtMmViYy00YzE4LTliYTEtMzgwMGQ3NTdiYjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDAwNTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYjA5ZTE4NTM0NmZkN2U1NDBkNjk2YWIzYjk5MDg2YzkyMjQ5OTZkNjhlNTdhZDhkYTIwNWQxYTllYzBmMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GHzBWmOWpTCfCWlikah_qpeULkud15ukuTeDrgZyf6s"> <img alt="Screenshot 2024-07-25 at 11 58 20 PM" width="200" src="https://private-user-images.githubusercontent.com/26853713/352424070-6ac8ab49-254e-46f2-923d-69c31d77b0c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDY5NzAsIm5iZiI6MTcyMjY0NjY3MCwicGF0aCI6Ii8yNjg1MzcxMy8zNTI0MjQwNzAtNmFjOGFiNDktMjU0ZS00NmYyLTkyM2QtNjljMzFkNzdiMGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDAwNTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNTE0YWMxZTQ1NjhmNzljNTM1YzkyYzNiZWEyMWNkZmMwOGQ1MjY3ZDU1MWU1ZjMwNzYwMGZlMzRjNGNlMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u_3vkFRwyJnByGxt-8lv9b33_oMByaCw9diaRZSH_10">
> but sometimes it suffers from poor restitching and facial deformation. <img alt="Screenshot 2024-07-26 at 12 01 03 AM" width="200" src="https://private-user-images.githubusercontent.com/26853713/352425516-0ea8e74a-4146-425c-b310-1fd15b2c445b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDY5NzAsIm5iZiI6MTcyMjY0NjY3MCwicGF0aCI6Ii8yNjg1MzcxMy8zNTI0MjU1MTYtMGVhOGU3NGEtNDE0Ni00MjVjLWIzMTAtMWZkMTViMmM0NDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDAwNTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYWVhYmYwOGY3Nzk3OWU0YmYzMzliN2RkNWY3NjBjYjk0ZmQ2MzA3NDEyMmUzZmRkZjViZDE3ZTc1YzNhZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sin6_iQAiEr4GdcCRCY466oCQXwji6rlwKr3RNrkJQ4"> <img alt="Screenshot 2024-07-26 at 12 01 35 AM" width="200" src="https://private-user-images.githubusercontent.com/26853713/352425797-b4e9fb21-6b63-49ec-badd-b7a34f328187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDY5NzAsIm5iZiI6MTcyMjY0NjY3MCwicGF0aCI6Ii8yNjg1MzcxMy8zNTI0MjU3OTctYjRlOWZiMjEtNmI2My00OWVjLWJhZGQtYjdhMzRmMzI4MTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDAwNTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYzA0NjM5MjExMzk2NmEzMWM0YzBiYWRjN2MxOTkyNWIyNDE3ZTM1NDRkNTZjZTcwMmE2NGI1YWE1ZGM3MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NQYg6Vu_3iWcsI_gaqbW61BKMb1cs-w6MHvw4E7kw8c"> <img alt="Screenshot 2024-07-26 at 12 01 19 AM" width="200" src="https://private-user-images.githubusercontent.com/26853713/352425673-7447e77e-17b2-4871-9b10-7aabc1e39aa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDY5NzAsIm5iZiI6MTcyMjY0NjY3MCwicGF0aCI6Ii8yNjg1MzcxMy8zNTI0MjU2NzMtNzQ0N2U3N2UtMTdiMi00ODcxLTliMTAtN2FhYmMxZTM5YWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDAwNTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNWI4ZGVlNzVhNzhmZmZhODM0ZGViZDU3YTI1NmI3NjVlZTg4YTYzY2M1ZDAwYWEyNmZiNWVhMzZmMGI5ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t7cNdGO7s67yOV3gPoAlAS6uwt8PBw866OtJgblfnO8">
> 
> Here's my code
> 
> ```
>     def execute_face_transfer(self, args: ArgumentConfig):
>         # for convenience
>         inf_cfg = self.live_portrait_wrapper.inference_cfg
>         crop_cfg = self.cropper.crop_cfg
> 
>         ######## load source input ########
>         img_rgb = args.source  # Assuming args.source is already a numpy array
>         img_rgb = resize_to_limit(img_rgb, inf_cfg.source_max_dim, inf_cfg.source_division)
>         source_rgb_lst = [img_rgb]
> 
>         ######## process driving info ########
>         driving_rgb = args.driving  # Assuming args.driving is already a numpy array
>         driving_rgb = resize_to_limit(driving_rgb, inf_cfg.source_max_dim, inf_cfg.source_division)
> 
>         ######## prepare for pasteback ########
>         flag_normalize_lip = inf_cfg.flag_normalize_lip
>         lip_delta_before_animation = None
> 
>         ######## process source info ########
>         if inf_cfg.flag_do_crop:
>             crop_info = self.cropper.crop_source_image(source_rgb_lst[0], crop_cfg)
>             if crop_info is None:
>                 raise Exception("No face detected in the source image!")
>             source_lmk = crop_info['lmk_crop']
>             img_crop_256x256 = crop_info['img_crop_256x256']
>         else:
>             source_lmk = self.cropper.calc_lmk_from_cropped_image(source_rgb_lst[0])
>             img_crop_256x256 = cv2.resize(source_rgb_lst[0], (256, 256))
> 
>         I_s = self.live_portrait_wrapper.prepare_source(img_crop_256x256)
>         x_s_info = self.live_portrait_wrapper.get_kp_info(I_s)
>         x_c_s = x_s_info['kp']
>         R_s = get_rotation_matrix(x_s_info['pitch'], x_s_info['yaw'], x_s_info['roll'])
>         f_s = self.live_portrait_wrapper.extract_feature_3d(I_s)
>         x_s = self.live_portrait_wrapper.transform_keypoint(x_s_info)
> 
>         if flag_normalize_lip and inf_cfg.flag_relative_motion and source_lmk is not None:
>             c_d_lip_before_animation = [0.]
>             combined_lip_ratio_tensor_before_animation = self.live_portrait_wrapper.calc_combined_lip_ratio(c_d_lip_before_animation, source_lmk)
>             if combined_lip_ratio_tensor_before_animation[0][0] >= inf_cfg.lip_normalize_threshold:
>                 lip_delta_before_animation = self.live_portrait_wrapper.retarget_lip(x_s, combined_lip_ratio_tensor_before_animation)
> 
>         if inf_cfg.flag_pasteback and inf_cfg.flag_do_crop and inf_cfg.flag_stitching:
>             mask_ori_float = prepare_paste_back(inf_cfg.mask_crop, crop_info['M_c2o'], dsize=(source_rgb_lst[0].shape[1], source_rgb_lst[0].shape[0]))
> 
>         ######## process driving info ########
>         driving_crop_info = self.cropper.crop_source_image(driving_rgb, crop_cfg)
>         if driving_crop_info is None:
>             raise Exception("No face detected in the driving image!")
>         driving_img_crop_256x256 = driving_crop_info['img_crop_256x256']
>         
>         I_d = self.live_portrait_wrapper.prepare_source(driving_img_crop_256x256)
>         x_d_info = self.live_portrait_wrapper.get_kp_info(I_d)
>         
>         ######## animate (single frame) ########
>         x_d_info = self.live_portrait_wrapper.get_kp_info(I_d)
>         R_d = x_d_info['R'] if 'R' in x_d_info.keys() else get_rotation_matrix(x_d_info['pitch'], x_d_info['yaw'], x_d_info['roll'])
> 
>         if inf_cfg.flag_relative_motion:
>             R_new = (R_d @ R_s.permute(0, 2, 1)) @ R_s
>             delta_new = x_s_info['exp'] + (x_d_info['exp'] - x_s_info['exp'])
>             scale_new = x_s_info['scale'] * (x_d_info['scale'] / x_s_info['scale'])
>             t_new = x_s_info['t'] + (x_d_info['t'] - x_s_info['t'])
>         else:
>             R_new = R_d
>             delta_new = x_d_info['exp']
>             scale_new = x_s_info['scale']
>             t_new = x_d_info['t']
> 
>         t_new[..., 2].fill_(0)  # zero tz
>         x_d_i_new = scale_new * (x_c_s @ R_new + delta_new) + t_new
> 
>         # Algorithm 1:
>         if not inf_cfg.flag_stitching and not inf_cfg.flag_eye_retargeting and not inf_cfg.flag_lip_retargeting:
>             # without stitching or retargeting
>             if flag_normalize_lip and lip_delta_before_animation is not None:
>                 x_d_i_new += lip_delta_before_animation
>         elif inf_cfg.flag_stitching and not inf_cfg.flag_eye_retargeting and not inf_cfg.flag_lip_retargeting:
>             # with stitching and without retargeting
>             if flag_normalize_lip and lip_delta_before_animation is not None:
>                 x_d_i_new = self.live_portrait_wrapper.stitching(x_s, x_d_i_new) + lip_delta_before_animation
>             else:
>                 x_d_i_new = self.live_portrait_wrapper.stitching(x_s, x_d_i_new)
>         else:
>             eyes_delta, lip_delta = None, None
>             if inf_cfg.flag_eye_retargeting and source_lmk is not None:
>                 c_d_eyes = self.live_portrait_wrapper.calc_ratio([driving_crop_info['lmk_crop']])[0]
>                 combined_eye_ratio_tensor = self.live_portrait_wrapper.calc_combined_eye_ratio(c_d_eyes, source_lmk)
>                 eyes_delta = self.live_portrait_wrapper.retarget_eye(x_s, combined_eye_ratio_tensor)
>             if inf_cfg.flag_lip_retargeting and source_lmk is not None:
>                 c_d_lip = self.live_portrait_wrapper.calc_ratio([driving_crop_info['lmk_crop']])[1]
>                 combined_lip_ratio_tensor = self.live_portrait_wrapper.calc_combined_lip_ratio(c_d_lip, source_lmk)
>                 lip_delta = self.live_portrait_wrapper.retarget_lip(x_s, combined_lip_ratio_tensor)
> 
>             if inf_cfg.flag_relative_motion:
>                 x_d_i_new = x_s + (eyes_delta if eyes_delta is not None else 0) + (lip_delta if lip_delta is not None else 0)
>             else:
>                 x_d_i_new = x_d_i_new + (eyes_delta if eyes_delta is not None else 0) + (lip_delta if lip_delta is not None else 0)
> 
>             if inf_cfg.flag_stitching:
>                 x_d_i_new = self.live_portrait_wrapper.stitching(x_s, x_d_i_new)
> 
>         out = self.live_portrait_wrapper.warp_decode(f_s, x_s, x_d_i_new)
>         I_p = self.live_portrait_wrapper.parse_output(out['out'])[0]
> 
>         # Convert BGR to RGB
>         I_p_rgb = cv2.cvtColor(I_p, cv2.COLOR_BGR2RGB)
>         source_rgb = cv2.cvtColor(source_rgb_lst[0], cv2.COLOR_BGR2RGB)
> 
>         if inf_cfg.flag_pasteback and inf_cfg.flag_do_crop and inf_cfg.flag_stitching:
>             I_p_pstbk = paste_back(I_p_rgb, crop_info['M_c2o'], source_rgb, mask_ori_float)
>             return I_p_pstbk
>         else:
>             return I_p_rgb
> ```
> 
> Is there anything I am doing wrong? Is the problem that my faces aren't always frontal? Plus, is there a way to manipulate more emotions through sliders – not only eyes and mouth? I noticed the "exp" is simply read from the driving video, and I figured it could be understandable as well!

have you solved this problem yet?

**Comment by killah-t-cell** [comment]
I did actually. I make it so the driving image emotions scale iteratively to the desired emotion (almost like mimicking the frames) and that did much better.

**Comment by YoungofNUAA** [comment]
> I did actually. I make it so the driving image emotions scale iteratively to the desired emotion (almost like mimicking the frames) and that did much better.

hi  bros,  Looking forward to your reply
