### ISSUE TITLE
How to fine

### ISSUE THREAD

**Issue by kigner** [KwaiVGI/LivePortrait#23]
How to fine tune, refer to the demonstration of fine-tuning animal faces in the paper

**Comment by cleardusk** [comment]
You can refer to the animals secion in Appendix : )

**Comment by EmmaThompson123** [comment]
@cleardusk @zzzweakman I want to finetune the animal generator model, my key issue is the animal model still use human dirving video in inference stage, but in training stage, can we use the animal image as driving, or if still use the human image as driving, how can we get the paired source animal image, driving human image and target animal image ? Thanks in the advance !
