### ISSUE TITLE
The portrait part shows black blocks

### ISSUE THREAD

**Issue by MinecraftSTL** [KwaiVGI/LivePortrait#231]
![0bb4ab142ab85e10a7b7db4dab143cf5](https://github.com/user-attachments/assets/a8fb54d1-9fec-4e1e-a9df-87ef509c32e0)

![c67c877aeea2a43e95df9e160b83a62d](https://github.com/user-attachments/assets/1f61f521-a1f8-4d74-93bc-900cf9a64f13)
CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz 
GPU: NVIDIA GeForce GTX 1660Ti
RAM: 16GB

[log.txt](https://github.com/user-attachments/files/16395772/log.txt)

**Comment by FurkanGozukara** [comment]
disable half precision in configs

**Comment by cleardusk** [comment]
@MinecraftSTL  Adding an `--no_flag_use_half_precision` to disable half precision, it is not supported on 1060.
```
# for CLI
python inference.py --no_flag_use_half_precision

# for Gradio
python app.py --no_flag_use_half_precision
```

**Comment by MinecraftSTL** [comment]
> disable half precision in configs



> @MinecraftSTL Adding an `--no_flag_use_half_precision` to disable half precision, it is not supported on 1660.
> 
> ```
> # for CLI
> python inference.py --no_flag_use_half_precision
> 
> # for Gradio
> python app.py --no_flag_use_half_precision
> ```
> 
> Or you can directly change this line to `flag_use_half_precision: bool = False`
> 
> https://github.com/KwaiVGI/LivePortrait/blob/5d1d71b1e25fd7b95c2a9616b4a3848c270ca6be/src/config/argument_config.py#L22

Thanks for the help, it works now

**Comment by MinecraftSTL** [comment]
> disable half precision in configs



> @MinecraftSTL Adding an `--no_flag_use_half_precision` to disable half precision, it is not supported on 1660.
> 
> ```
> # for CLI
> python inference.py --no_flag_use_half_precision
> 
> # for Gradio
> python app.py --no_flag_use_half_precision
> ```
> 
> Or you can directly change this line to `flag_use_half_precision: bool = False`
> 
> https://github.com/KwaiVGI/LivePortrait/blob/5d1d71b1e25fd7b95c2a9616b4a3848c270ca6be/src/config/argument_config.py#L22

Thanks for the help, it works now
