### ISSUE TITLE
我不知道是出了什么问题

### ISSUE THREAD

**Issue by lambbigcc** [KwaiVGI/LivePortrait#233]
如图
<img width="1203" alt="屏幕截图 2024-07-27 200419" src="https://github.com/user-attachments/assets/b42f6e04-09c1-43e8-a3fa-b54668432830">
有没有人可以帮助我解决一下

**Comment by cleardusk** [comment]
@lambbigcc 
是不是问错地方了🤣？
应该在ComfyUI的repo：https://github.com/kijai/ComfyUI-LivePortraitKJ

**Comment by lambbigcc** [comment]
您好，很抱歉发错地方了，我是一位初学者，可以告诉我我应该发到什么地方么，谢谢！












高洋(lamb)
***@***.***






---原始邮件---
发件人: "Jianzhu ***@***.***&gt;
发送时间: 2024年7月27日(周六) 晚上11:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [KwaiVGI/LivePortrait] 我不知道是出了什么问题 (Issue #233)




 
@lambbigcc
 是不是问错地方了🤣？
 应该在ComfyUI的repo：https://github.com/kijai/ComfyUI-LivePortraitKJ

**Comment by lambbigcc** [comment]
谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月30日(星期二) 下午2:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KwaiVGI/LivePortrait] 我不知道是出了什么问题 (Issue #233)














  
您好，很抱歉发错地方了，我是一位初学者，可以告诉我我应该发到什么地方么，谢谢！ 高洋(lamb) @.***
  
因为您使用的是ComfyUI的repo，您可以在这里进行询问。
