### ISSUE TITLE
Error when cloning the code 

### ISSUE THREAD

**Issue by S7ORMD5** [KwaiVGI/LivePortrait#239]
i get this error, im new to this sort of ai stuff, so maybe somebody could help me fix this?

Cloning into 'LivePortrait'...
remote: Enumerating objects: 664, done.
remote: Counting objects: 100% (428/428), done.
remote: Compressing objects: 100% (266/266), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 2441 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by cleardusk** [comment]
@S7ORMD5 
You can also download the code with zip format:
![image](https://github.com/user-attachments/assets/c9984b83-3ec4-4b3e-a569-c7c6e571d9ee)

Or, Windows users can download one-click package: https://huggingface.co/cleardusk/LivePortrait-Windows/blob/main/LivePortrait-Windows-v20240725.zip

**Comment by FurkanGozukara** [comment]
internet related error

you can try cloudflare warp vpn - free
