### ISSUE TITLE
huggingface.co国内上不了

### ISSUE THREAD

**Issue by ZJH-SCUT** [KwaiVGI/LivePortrait#243]
(LivePortrait) [jhzhang@hostname LivePortrait]$ git clone https://huggingface.co/KwaiVGI/LivePortrait temp_pretrained_weights
Cloning into 'temp_pretrained_weights'...
fatal: unable to access 'https://huggingface.co/KwaiVGI/LivePortrait/': Failed to connect to 2001::6ca0:a5d3: Network is unreachable
国内似乎上不了huggingface.co，想问一下有没有解决办法。

**Comment by FurkanGozukara** [comment]
try warp vpn it is free cloudflare

**Comment by cleardusk** [comment]
@ZJH-SCUT  百度云，请仔细看readme
https://pan.baidu.com/share/init?surl=MGctWmNla_vZxDbEp2Dtzw&pwd=z5cn

**Comment by ZJH-SCUT** [comment]
国内有镜像网址，把clone网址改为https://hf-mirror.com/KwaiVGI/LivePortrait就可以了

**Comment by mir-xiong** [comment]
> 国内有镜像网址，把clone网址改为[https://hf-mirror.com/KwaiVGI/LivePortrait就可以了](https://hf-mirror.com/KwaiVGI/LivePortrait%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BA%86)

这是怎么搭建的呀
