### ISSUE TITLE
怎么设置用cpu跑呀

### ISSUE THREAD

**Issue by bageers0** [KwaiVGI/LivePortrait#247]
怎么设置用cpu跑呀

**Comment by henghamao** [comment]
argument_configy.py
line 24:
flag_force_cpu: bool = True

However, it is WIP. Not sure it would work.

**Comment by yu1anan** [comment]
CPU我试过，可以跑，但是可能是机器的问题，我跑的时候发现得把self.inference_ctx()注释掉才行

**Comment by szxszx0611** [comment]
> CPU我试过，可以跑，但是可能是机器的问题，我跑的时候发现得把self.inference_ctx()注释掉才行

改哪个文件啊？我怎么跑不了CPU
