### ISSUE TITLE
Select GPU

### ISSUE THREAD

**Issue by wesleyliwewa** [KwaiVGI/LivePortrait#248]
Hello, I have 2 GPUs in my PC, and I would like to know is it possible to set which GPU to use? Thank you.

**Comment by aihacker111** [comment]
device_id in config file or devive , you can monitor it like this: device_id = 0 (First GPU in your machine), device_id = 1 (Second GPU) or device = 'cuda:0' (First GPU) or device = 'cuda:1' (Second GPU)

**Comment by wesleyliwewa** [comment]
Thank you for your reply.
So I want to make sure that which file I should modify and add like device_id = 0 or device_id = 1? 
In the run_windows.bat?
Thanks.

**Comment by aihacker111** [comment]
@wesleyliwewa  Yes bro
<img width="587" alt="Screenshot 2024-07-30 at 14 35 10" src="https://github.com/user-attachments/assets/b036c558-a583-4030-977a-52b34220f5ec">
change this in inference_config.py , it's automatic set your device_id = 0 in first GPU

**Comment by zzzweakman** [comment]
> Hello, I have 2 GPUs in my PC, and I would like to know is it possible to set which GPU to use? Thank you.

Thank you for your attention. As @aihacker111 mentioned, you can select the GPU by using the command `python3 inference.py --device_id 1`.

**Comment by zzzweakman** [comment]
> Hello, I have 2 GPUs in my PC, and I would like to know is it possible to set which GPU to use? Thank you.



> Thank you for your reply. So I want to make sure that which file I should modify and add like device_id = 0 or device_id = 1? In the run_windows.bat? Thanks.

Thanks for your attention. To modify the GPU id, you should change the `device_id` in the [argument_config.py](https://github.com/KwaiVGI/LivePortrait/blob/main/src/config/argument_config.py#L24) file.

**Comment by FurkanGozukara** [comment]
better way could be set cuda visible devices in running .bat file or on cmd

SET CUDA_VISIBLE_DEVICES=0
SET CUDA_VISIBLE_DEVICES=1

**Comment by Rizwanali324** [comment]
> better way could be set cuda visible devices in running .bat file or on cmd
> 
> SET CUDA_VISIBLE_DEVICES=0 SET CUDA_VISIBLE_DEVICES=1

can I set device id as list for kaggle dual GPU uses
