### ISSUE TITLE
Error When Using the --share Flag

### ISSUE THREAD

**Issue by talgreen1** [KwaiVGI/LivePortrait#256]
Hello,

I'm trying to access the web UI from another machine on the network.

To do this, I'm using the --share flag in the 'run_windows.bat' file like this:
```
start /B python app.py --share
```

However, I'm encountering the following error:
```
OSError: Cannot find empty port in range: 13564-13564. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the server_port parameter to launch().
```

Can anyone help me figure out what I'm missing?

Thanks,
Tal.

**Comment by wangbinxu** [comment]
--share --server-name=0.0.0.0

**Comment by cleardusk** [comment]
@talgreen1 You can follow @wangbinxu 's advice, e.g., 
```bat
start /B python app.py --share --server_name="0.0.0.0"
```

**Comment by talgreen1** [comment]
Thank you very much. It worked.
