### ISSUE TITLE
Not getting good results with animal

### ISSUE THREAD

**Issue by nitinmukesh** [KwaiVGI/LivePortrait#259]
The sample images provided works fine but if I use another image the results are bad.
Anything specific required to make it work
Also 90% of images fails with raise Exception("No face detected in the source image!")

https://github.com/user-attachments/assets/6ddc9304-cc4b-4171-ae47-e97f3a943835

https://github.com/user-attachments/assets/068830f8-8a55-48d8-a58a-8d979e2a0d7e

**Comment by cleardusk** [comment]
Thanks for your attention @nitinmukesh 

Could you please provide these original cats images for us to debug?

**Comment by nitinmukesh** [comment]
@cleardusk 

Thank you. Please find attached zip
[images.zip](https://github.com/user-attachments/files/16454878/images.zip)

**Comment by cleardusk** [comment]
Thanks! @nitinmukesh 

And, can we pick several cases from these zip as the default example inputs? (only for showcase)

**Comment by nitinmukesh** [comment]
@cleardusk 

It's all yours, no issues in using in anyway. All generated through AI so no copyright.

**Comment by nitinmukesh** [comment]
New version is much better,
