### ISSUE TITLE
Making the output video larger

### ISSUE THREAD

**Issue by talgreen1** [KwaiVGI/LivePortrait#261]
Hi,

The output resolution is always 1280x718.
Is there any way to make it larger?

Tal.

**Comment by zzzweakman** [comment]
@talgreen1  Change `source_max_dim `
https://github.com/KwaiVGI/LivePortrait/blob/cf74ed3c16f9d0448cece636109aa47ee29527b5/src/config/inference_config.py#L54

**Comment by talgreen1** [comment]
Thank you!
