### ISSUE TITLE
Update on The One-Click Installer for Windows 11?

### ISSUE THREAD

**Issue by MarsEverythingTech** [KwaiVGI/LivePortrait#267]
Hello,

I noticed there has been an update to the repo, and was wondering if it will be applied to the One-Click Installer for Windows 11.

Thanks in advance

**Comment by zzzweakman** [comment]
@MarsEverythingTech  Thanks for your attention. The new version of the One-Click Installer for Windows is indeed on our schedule : )

**Comment by MarsEverythingTech** [comment]
> @MarsEverythingTech Thanks for your attention. The new version of the One-Click Installer for Windows is indeed on our schedule : )

Hello, 

Thank you so much! I appreciate it. I am also looking forward to the ONNX and TensorRT implementation for faster processing.

**Comment by zzzweakman** [comment]
@MarsEverythingTech The new version of the One-Click Installer for Windows is now available! Check our latest [update](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#-updates)!

**Comment by MarsEverythingTech** [comment]
> @MarsEverythingTech The new version of the One-Click Installer for Windows is now available! Check out our latest [update](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#-updates)!

Amazing. Thank you so much. I appreciated it :)
