### ISSUE TITLE
Do you plan to publish the Portrait Video Editing code?

### ISSUE THREAD

**Issue by D-Mad** [KwaiVGI/LivePortrait#27]

**Comment by cleardusk** [comment]
It is on the schedule, but may taking several days. Stay tuned please!

**Comment by AlonDan** [comment]
Thank you for sharing such amazing project! ❤

Video source will be amazing to test!
Will **Multiple-Faces** and select **SPECIFIC Face** (if multiple faces on source image/video) will be added in the future?

**Comment by mhsin321** [comment]
> It is on the schedule, but may taking several days. Stay tuned please!

  awww wow u made my day so so its mean we can put any video with any random emotion and movement and its can change face movements and feature and emotion through given new audio driven and impose its emotions too in converted videos like photos ?? :O huh

**Comment by Jie-zju** [comment]
> It is on the schedule, but may taking several days. Stay tuned please!

@cleardusk Or Instruction on how to realize  Portrait Video Editing code based currnet code?

**Comment by zzzweakman** [comment]
Just pull the latest updates to enjoy the new video editing features :) @Jie-zju @mhsin321 @D-Mad @AlonDan
