### ISSUE TITLE
can not run the animal version

### ISSUE THREAD

**Issue by Uniky** [KwaiVGI/LivePortrait#274]
<img width="1434" alt="7540461397c660f7164241ed02ebaae" src="https://github.com/user-attachments/assets/968bc472-6b5f-4e64-8662-7ed6dfa0858f">
The normal version works fine

**Comment by Alucard24** [comment]
take a look here:
https://github.com/KwaiVGI/LivePortrait/issues/270#issuecomment-2266650894

;)

**Comment by zzzweakman** [comment]
Many thanks to @Alucard24 and @v3ucn for their assistance in #270 and #273. The error has now been resolved.
