### ISSUE TITLE
Installation Issue on MacBook Pro M3: Tokenizers Compilation Error

### ISSUE THREAD

**Issue by hunglsxx** [KwaiVGI/LivePortrait#276]
Hello, I'm having an issue when running the command pip install -r requirements_macOS.txt. The error seems to stem from the tokenizers processing with the following message: "error: could not compile tokenizers (lib) due to 1 previous error; 3 warnings emitted."

I'm using a MacBook Pro M3 and followed the installation steps as outlined in the Introduction section. I have attached an image with details of the error.

Please help. Thank you very much.
<img width="1498" alt="Screenshot 2024-08-04 at 12 47 49" src="https://github.com/user-attachments/assets/35bc0daf-4f5e-4b0b-bba8-3e1ada7c2a35">

**Comment by zzzweakman** [comment]
@hunglsxx  You can try commenting out [this line](https://github.com/KwaiVGI/LivePortrait/blob/main/requirements_base.txt#L21) first, and then install again. We will fix this environment issue later. Please note that the animal functionality is not available on Mac yet.

**Comment by hunglsxx** [comment]
@zzzweakman  Thank you for your quick response. It works for me !!
