### ISSUE TITLE
opencv报错

### ISSUE THREAD

**Issue by nanpa** [KwaiVGI/LivePortrait#279]
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
有个错误提示，这个怎么解决呢？

**Comment by zzzweakman** [comment]
@nanpa 您可以看一下这个issue #138.

**Comment by nanpa** [comment]
感谢，解决了，不能放到默认的图片文件夹，自建一个无中文名的文件夹解决
