### ISSUE TITLE
Head wobble

### ISSUE THREAD

**Issue by Inferencer** [KwaiVGI/LivePortrait#28]
I managed to remove wobble of shoulders by masking driving vid so only the head is visible this had a great effect.

The head on results from certain driving vids can have bad wobble caused by the head enlarging, I imagine this is due to a bad driving vid affecting the alignment crop radius, on another project I was able to set a persistent crop radius based on the most common value that worked rather well what are your thoughts on resolving this?

I don't have the driving vid for this or the settings so if anybody has all the settings checked and the concanated file and a noticable head wobble then please upload 

https://github.com/KwaiVGI/LivePortrait/assets/121839197/24bb67f8-9752-4d3f-b8fd-202c38666fe2

**Comment by cleardusk** [comment]
Could you provide the original driving video (without any cropping) for us to do analysis?

**Comment by huanggou666** [comment]
the camera seem need to be still

**Comment by Inferencer** [comment]
> the camera seem need to be still

yeah you are right it wasn't one of mine, seems the user just held the camera in their hand

**Comment by buddylee7** [comment]
Can you take the original video you use and apply stabilization with tracking and see if that works?

**Comment by Inferencer** [comment]
> Can you take the original video you use and apply stabilization with tracking and see if that works?

wasnt mine, have since informed user to put her head on wall and use static camera results seem fine now

https://github.com/KwaiVGI/LivePortrait/assets/121839197/eeef8183-c4b9-4be3-a1d1-179a53512f88

**Comment by xiao-keeplearning** [comment]
@Inferencer Hi~
How did you solve the issue of removing the wobble of the shoulders? Could you explain the method you used to mask the driving video so that only the head is visible?
