### ISSUE TITLE
 No module named 'LivePortrait.src.utils.retargeting_utils'

### ISSUE THREAD

**Issue by Elminsst** [KwaiVGI/LivePortrait#289]
![6a059bf6ff7a4c82675bf84a1f0f01d](https://github.com/user-attachments/assets/1f45702e-90b2-40c9-8222-4dd81210cdae)
how can i fix this？
thx！！

**Comment by zzzweakman** [comment]
@Elminsst It looks like you are using the ComfyUI repo, not our repo, so we are unable to provide assistance.
