### ISSUE TITLE
requirements_macOS ERROR torch==2.3.0 

### ISSUE THREAD

**Issue by wming3** [KwaiVGI/LivePortrait#295]
pip install -r requirements_macOS.txt  

ERROR: Could not find a version that satisfies the requirement torch==2.3.0 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==2.3.0

Python 3.9.19
pip 24.2 from /opt/anaconda3/envs/LivePortrait/lib/python3.9/site-packages/pip (python 3.9)
mac os 14.6
cpu：Intel

**Comment by hankknight** [comment]
You can check torch download page to figure out your mac operation system is availabled, url is: `https://download.pytorch.org/whl/torch/` , otherwise you might build torch from source to slove your problem, this is my solution , hope it can help you.

**Comment by cleardusk** [comment]
@wming3 I think 2.2.2 works too. The model does not heavily rely on specific version of PyTorch.

**Comment by zzzweakman** [comment]
@wming3 From our tests, even `pytorch==1.10.1` works. You can try downgrading your PyTorch version.

**Comment by wming3** [comment]
cpu：Intel 
cpu：Intel 
cpu：Intel
