### ISSUE TITLE
How to make a driving video?

### ISSUE THREAD

**Issue by 2502128021** [KwaiVGI/LivePortrait#3]
as the title describes, can u explain how to make a driving video like the samples in ./assets/examples/driving

**Comment by Inferencer** [comment]
Record yourself with little shoulder movement, in a video editing app change the resolution to 512x512, then zoom in on the face so it takes up 60-90% of the screen. It should output a 512x512 of just your face.

Best to keep it 25fps.

**Comment by 2502128021** [comment]
thx for your cool work and reply, I'll try what you suggested.
but I still have some questions:
1.why the driving video should be with little shoulder movement, since you have offered --no-flag-stiching. if I set it, the ref image should move like driving video, is that right?
2.why need to zoom in on the face, you have mentioned in your paper, you made trainingset like TalkingHead-1KH, so face ratio should not as big as 60-90%, why there is a difference between training and inference?
 hope to get your reply!

**Comment by justinjohn0306** [comment]
> thx for your cool work and reply, I'll try what you suggested. but I still have some questions: 1.why the driving video should be with little shoulder movement, since you have offered --no-flag-stiching. if I set it, the ref image should move like driving video, is that right? 2.why need to zoom in on the face, you have mentioned in your paper, you made trainingset like TalkingHead-1KH, so face ratio should not as big as 60-90%, why there is a difference between training and inference? hope to get your reply!

you can run this script for making a driving video: https://github.com/KwaiVGI/LivePortrait/blob/main/video2template.py

**Comment by JuncFang-git** [comment]
> We are planning to provide functions to create a driving video from a raw video. Stay tuned! @2502128021 @justinjohn0306

Waiting for your update. I am making a driving video but get some errors at lip area. Could you give me some suggestions?

https://github.com/KwaiVGI/LivePortrait/assets/76929740/0ba24493-8859-45ea-bbc5-5d5ecba85b87

**Comment by cleardusk** [comment]
@justinjohn0306 Currently, if you use the `relation motion` mode, the first frame of the driving video should be neutral! It will refer the first frame as the anchor.

**Comment by zzzweakman** [comment]
> as the title describes, can u explain how to make a driving video like the samples in ./assets/examples/driving

We are pleased to inform you that LivePortrait now supports automatic processing of raw videos. You can find more details on how to create a driving video at [here](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#driving-video-auto-cropping)!
