### ISSUE TITLE
Anybody have success installing animal inference dependency (xpose) in colab/kaggle ?

### ISSUE THREAD

**Issue by x4080** [KwaiVGI/LivePortrait#307]
```
%cd src/utils/dependencies/XPose/models/UniPose/ops
!python setup.py build install
```
this part show lot of warning deprecation etc and when running 
```
!python inference_animals.py -s assets/examples/source/s39.jpg -d assets/examples/driving/wink.pkl --no_flag_stitching --driving_multiplier 1.75
```

it stops because cannot find required files

**Comment by FurkanGozukara** [comment]
Yes I did on a free kaggle 

The notebook shared in this tutorial got updated

https://youtu.be/wG7oPp01COg?si=OvaNJ6SpEL03owX_

**Comment by x4080** [comment]
Ok, solve it by uinstalling torch first
