### ISSUE TITLE
Hi! i have a error when I use tyro.

### ISSUE THREAD

**Issue by NeuroDonu** [KwaiVGI/LivePortrait#316]
Hi!
![image](https://github.com/user-attachments/assets/ab73336d-0ad8-4ef6-b286-b1dcbd56a728)
i get this error, if y use args = tyro.cli(ArgumentConfig) instead of directly transmitting args = ArgumentConfig(). I use Colab. Initially I tried to run just via python app.py, but I ran into the application loading endlessly on this one:
![image](https://github.com/user-attachments/assets/f972ef94-f22e-46cf-9272-3c27281de648)
I now remove tyro.cli and pass args directly:
![image](https://github.com/user-attachments/assets/c06e4974-6b8e-4efe-a207-c405cd4895a9)
(but I still can't run through python app.py - I have to directly add the code to the cell and use it that way. hope you can tell me how to fix this!)

**Comment by cleardusk** [comment]
`tyro` is designed for CLI, just remove `tyro` if you run it in colab, the same in app.py.
: ) @NeuroDonu

**Comment by NeuroDonu** [comment]
hmm, thanks for the help!
