### ISSUE TITLE
unsupported Microsoft Visual Studio version；安装失败“MultiScaleDeformableAttention”

### ISSUE THREAD

**Issue by Tinaisok** [KwaiVGI/LivePortrait#323]
[根据前三步先跑一下inference.py，能跑通](https://github.com/KwaiVGI/LivePortrait/issues/321)
![image](https://github.com/user-attachments/assets/0d6a920f-829d-4dca-b798-873393888b11)
接着
cd src/utils/dependencies/XPose/models/UniPose/ops
python setup.py build install
![image](https://github.com/user-attachments/assets/9a0da3a2-8062-4df0-979f-0d617d47c59d)
出问题了 Visual Studio version版本不支持，我安装的是2022版，不知道为什么也不行
![image](https://github.com/user-attachments/assets/9ee7fea7-16b9-4ddf-9b7d-4d940482475b)
如果不管这个bug，继续向下执行代码，回到项目原目录，执行
cd  C:\Users\19535\LivePortrait
python inference_animals.py -s assets/examples/source/s39.jpg -d assets/examples/driving/wink.pkl --driving_multiplier 1.75 --no_flag_stitching
出现ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'
![image](https://github.com/user-attachments/assets/eb0ae831-02a4-4eea-8384-8109f993a2da)
试图手动安装 MultiScaleDeformableAttention,安装失败
![image](https://github.com/user-attachments/assets/e06580a0-acb3-4ad2-ab21-72325e0b28ab)
查了一下之前安装失败的setup.py，查到了MultiScaleDeformableAttention的安装信息，但是还是不知道如何手动安装
![image](https://github.com/user-attachments/assets/cd0d0693-ed46-43ae-bea6-48eb9ea8c210)
有人遇到一样的问题了吗，现在能想到的解决方案就是在安装setup环节搞定visual studio版本的问题（比如使用The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution，但具体怎么用还不清楚），解决不了就解决最后一步的MultiScaleDeformableAttention的手动安装，这个手动安装也暂时不清楚如何下手，希望有人能帮忙解答一下，感激不尽！！！

**Comment by gaizi123** [comment]
遇到了同样的问题

**Comment by zzzweakman** [comment]
@gaizi123 @Tinaisok 感谢关注，有两个解决办法。 1. 直接使用我们的一件安装包，环境已经打包进去了。 2. 下载VS 2019，可以查看一下这个[链接](https://blog.csdn.net/adminstate/article/details/128939556)。

**Comment by zzzweakman** [comment]
@Tinaisok 祝您使用愉快

**Comment by XeoOuYang** [comment]
我已经安装vs2019，但是还是安装XPose失败。
LINK : fatal error LNK1104: 无法打开文件“build\temp.win-amd64-cpython-39\Release\LivePortrait\src\utils\dependencies\XPose\models\UniPose\ops\src\cpu\MultiScaleDeformableAttention.cp39-wi4.exp”

我去该目录下查看，确实不存在这个文件。
![image](https://github.com/user-attachments/assets/34638961-8b87-46cf-8432-b0dc76eb1f83)

**Comment by XeoOuYang** [comment]
去原始X-Pose工程build出来，然后再把build好的产物拷贝过来，直接install。如果不行，就从X-Pose的环境中，去site-package复制过来。
