### ISSUE TITLE
Missing 'face_recon_wrapper'

### ISSUE THREAD

**Issue by QUTGXX** [KwaiVGI/LivePortrait#33]
How can I crop a video to prepare it for inference tasks?

**Comment by zzzweakman** [comment]
> How can I crop a video to prepare it for inference tasks?

Thank you for your patience! We are pleased to inform you that LivePortrait now supports automatic video cropping. You can find more details [here](https://github.com/KwaiVGI/LivePortrait#video-cropping).

**Comment by QUTGXX** [comment]
> > How can I crop a video to prepare it for inference tasks?
> 
> Thank you for your patience! We are pleased to inform you that LivePortrait now supports automatic video cropping. You can find more details [here](https://github.com/KwaiVGI/LivePortrait#video-cropping).

Thanks for your sharing! I git pull the latest code, but it also raises an error. 
![image](https://github.com/KwaiVGI/LivePortrait/assets/36947214/97f76e8e-47a5-48f0-a9c4-a556ba171ef8)

**Comment by cleardusk** [comment]
Weird, did you check the newst commit is the same as origin/main? @QUTGXX

**Comment by QUTGXX** [comment]
> Weird, did you check the newst commit is the same as origin/main? @QUTGXX

yes, did u try that? did u  execute successfully?

**Comment by cleardusk** [comment]
I am the owner&maintainer of this repo : )

**Comment by QUTGXX** [comment]
> I am the owner&maintainer of this repo : )

Thanks for your reply, Can u help me address this issue? I tried to re-pull the code and still raise this error.

**Comment by zzzweakman** [comment]
> > > How can I crop a video to prepare it for inference tasks?
> > 
> > 
> > Thank you for your patience! We are pleased to inform you that LivePortrait now supports automatic video cropping. You can find more details [here](https://github.com/KwaiVGI/LivePortrait#video-cropping).
> 
> Thanks for your sharing! I git pull the latest code, but it also raises an error. @zzzweakman ![image](https://private-user-images.githubusercontent.com/36947214/347803135-97f76e8e-47a5-48f0-a9c4-a556ba171ef8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTk4NDUsIm5iZiI6MTcyMDY5OTU0NSwicGF0aCI6Ii8zNjk0NzIxNC8zNDc4MDMxMzUtOTdmNzZlOGUtNDdhNS00OGYwLWE5YzQtYTU1NmJhMTcxZWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDEyMDU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmM2EwMzRhNzg2NjVkMzNlMDk5YzIzY2U3NTllMjE2NWIwZmQ4YTY2N2QxZDk3YThmN2ZlZDUzNzJiZmFkNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rUnyjxKqIi30b7cGzCUub1uXQVB8HQainLqwY9SKQyM)

t seems the error might be caused by the argument --flag-crop-driving-video. Try using --flag_crop_driving_video instead. @QUTGXX

**Comment by cleardusk** [comment]
Both `--flag-crop-driving-video` and `--flag_crop_driving_video` should work.Could you please paste your execution command? @QUTGXX

**Comment by QUTGXX** [comment]
> I am the owner&maintainer of this repo : )



> Both `--flag-crop-driving-video` and `--flag_crop_driving_video` should work.Could you please paste your execution command? @QUTGXX

flag_crop_driving_video works!!!!!
