### ISSUE TITLE
【新功能请求】输入源面部（角度）对齐功能 ？Face Angle Alignment

### ISSUE THREAD

**Issue by juntaosun** [KwaiVGI/LivePortrait#335]
大致情景：检测并对齐（源/目标）两个画面的第一帧人脸角度。

因为已经捕获到面部及面部的关键点信息，
猜测：实际上程序应该能判断两个头部的初始角度差异？

（1）通过对比（输入源图片/目标视频第一帧）的初始头部的差异值（转向角度，眼睛/嘴巴张合等），
（2）然后用程序的方式，调节输入源图像，与目标视频的第一帧初始角度，保持一致性。

这样有利于快速得到最优结果；
而不必每次在第一帧都要进行人工对齐，或挑选源图片人像角度。

希望有人对此感兴趣，最好能够实现它？

---

General scenario: Detect and align the face angles of the first frame of two images (source/target).

Because the face and key points of the face have been captured,
Guess: In fact, the program should be able to determine the initial angle difference of the two heads?

(1) By comparing the initial head difference values ​​(turning angle, eye/mouth opening, etc.) of (input source image/target video first frame),

(2) Then use the program to adjust the input source image to keep it consistent with the initial angle of the first frame of the target video.

This helps to quickly get the best result;
there is no need to manually align the first frame or select the source image portrait angle every time.

I hope someone is interested in this, and it would be best if it can be implemented?

**Comment by siyehua** [comment]
这个已经实现了吗？我看项目貌似只实现了对眼睛，嘴巴的闭合度计算，其他的好像没有，通过 `utils.retargeting_utils` 实现的。
但是我要计算当前用户的人脸是否歪头，是否微笑，微笑了多少度等等，这些目前还是没有的
