### ISSUE TITLE
Question : can animation_region value be multiple like eyes, lip ? Or only just 1

### ISSUE THREAD

**Issue by x4080** [KwaiVGI/LivePortrait#345]
The reason for the question is, this is a good method to remove head wobbling if we just wanted to copy eyes and lip movements only

Thanks, and keep up the great work

**Comment by x4080** [comment]
ok so the answer is using exp

**Comment by Hingwing** [comment]
what if I just want the eyes & exp & head pose except the lips? I think the need for this project still makes sense，hope for new progress
