### ISSUE TITLE
强制cpu运行报错“Currently, AutocastCPU only support Bfloat16 as the autocast_cpu_dtype”，需要怎么修改？

### ISSUE THREAD

**Issue by wzh52112** [KwaiVGI/LivePortrait#347]

**Comment by zzzweakman** [comment]
感谢关注，您可以试试将[这个参数](https://github.com/KwaiVGI/LivePortrait/blob/main/src/config/argument_config.py#L21)设置为False。

**Comment by Apokar** [comment]
我修改成了False之后，还是一样的报错，这是怎么回事呢

**Comment by Apokar** [comment]
我修改成了False之后，还是一样的报错，请问这是怎么回事呢 @zzzweakman
