### ISSUE TITLE
My character has big eyes and does not close completely

### ISSUE THREAD

**Issue by vghcode** [KwaiVGI/LivePortrait#36]
This is an amazing project, awesome work.
I have two issues:
1. My character doesn't close her eyes.
2. I have a wolf character, and there is an error with face detection. it doesn't work with animals?
![s12--d7_concat mp4_snapshot_00 03 633](https://github.com/KwaiVGI/LivePortrait/assets/135419485/4acde731-b83e-4b0c-b835-c1d1012ba322)

**Comment by Inferencer** [comment]
for the animals no as they didnt provide a trained animal model

**Comment by Inferencer** [comment]
done some tests seems it just cant blink when the eyes are huge

**Comment by zzzweakman** [comment]
1.  To control eye closure, try setting the `flag_eye_retargeting` parameter to `True` during inference. You can find this parameter in the file `src/config/argument_config.py`.
2. Due to some limitations, we are sorry that we can not provide animal models now. However, you can find some details about the training of the animal models in the supplementary materials of our paper.
@vghcode

**Comment by vghcode** [comment]
Thank you for your response.
I tried the setting and it worked! However, the eyebrow and lip movements are limited. In fact, they do not move at all, and the focus is on the eyes.
@zzzweakman

![s12--d7_concatnew mp4_snapshot_00 03 485](https://github.com/KwaiVGI/LivePortrait/assets/135419485/bbbb57c8-ea4a-41fe-b60b-3d1e4d3d948c)

**Comment by FurkanGozukara** [comment]
when this is enabled you lose head movement

https://github.com/KwaiVGI/LivePortrait/issues/45

**Comment by vghcode** [comment]
> when this is enabled you lose head movement
> 
> #45

thank you

**Comment by FurkanGozukara** [comment]
> > when this is enabled you lose head movement
> > #45
> 
> If you want both stitching and retargeting, you need to set flag_relative to False. (which default is True)

it worked but it is horrific :D thanks for the info

https://github.com/KwaiVGI/LivePortrait/assets/19240467/3fb39053-95ac-4f9f-a92b-9825440f103a

**Comment by markson14** [comment]
> > > when this is enabled you lose head movement
> > > #45
> > 
> > 
> > If you want both stitching and retargeting, you need to set flag_relative to False. (which default is True)
> 
> it worked but it is horrific :D thanks for the info
> 
>  Biden_Photo_Big_concat_sound_0001.mp4 
> ok here another try
> 
> 0% extra eyes open 30% extra mouth open
> 
>  Biden_Photo_Big_concat_sound_0002.mp4

Lol, it looks funny though.
