### ISSUE TITLE
Driving video first frame limitation problem, Open Mouth in Initial Frame Causes Generated Video to Have Closed Mouth

### ISSUE THREAD

**Issue by P2Oileen** [KwaiVGI/LivePortrait#368]
As explained in the README, the first frame should have a "neutral expression." Additionally, as mentioned in the [GitHub issue comment](https://github.com/KwaiVGI/LivePortrait/issues/184#issuecomment-2241713736), the first frame must have the mouth closed. 

Could you explain why this is necessary for generating proper facial expressions? I've noticed that if the mouth is open in the first frame, the generated video's lips will remain closed throughout the entire video. 

Sometimes, the driving video's first frame may not have a neutral expression or a closed mouth. Are there any methods to overcome this limitation? I understand that simply concatenating a frame with a neutral expression to the very beginning of the video might solve the problem, but sometimes it's hard to obtain such a frame. 

I have also tried recording a video with a neutral face, generating the pkl file from the first frame, and then concatenating it to the front of other pkl files. However, the generated result turned out to be quite odd.

Thank you for any assistance you can provide!

**Comment by P2Oileen** [comment]
P.S. After reading the paper and the code, I tried to add `--no_flag_relative_motion` while processing. I think this might directly use the exp of each frame of driving video instead of calculating the diff between the intermediate frame and the first frame, but the result seemed not to be like this.

**Comment by P2Oileen** [comment]
I found a way to make mouth open like the input video, but the result is not as good as usual. The mouth open ratio is correct but the movement looks strange.
My setting:
```
flag_lip_retargeting: bool = True
flag_relative_motion: bool = False
flag_eye_retargeting: bool = False
```

**Comment by P2Oileen** [comment]
I have noticed this problem is mainly related to `driving option (i2v)` `expression-friendly`, this is a default setting, which might cause this problem. I firmly recommend to choose `pose-friendly` option while processing until this bug is fixed.

**Comment by cleardusk** [comment]
Thanks for your feedback @P2Oileen 
A fix https://github.com/KwaiVGI/LivePortrait/pull/372 has been merged : )

**Comment by simplyexperimental** [comment]
I don't think this is a bug - I'm pretty sure the AI was trained with neutral expressions and it's why the documents say to use a neutral expression however it's quite easy to get around this you only need to open the video in your video editor and look for a frame that has a neutral expression and copy that frame over to the first frame of the video and hit save.
If your video does not contain a neutral expression what you can do is save any frame that looks straight at the camera - even if it has mouth open it's ok - upload it and use the retarget feature - and play with the settings to make the face neutral then save as a image then upload that to your video editor as the first frame combined into your original video then save and it should work fine. Trainer Tips:
-Make sure target and source videos match in frame rate to avoid audio sync issues. You can use video editor to do this too.
-The retargeted image will save as 720p but that doesn't matter the AI will understand it as long as it's in the first frame and covers the same canvas space as the original 1080p video etc - it's fine even if the second frame has a crazy expression.

**Comment by P2Oileen** [comment]
@simplyexperimental  I had some private communication with the first author of this article, and currently, both of us believe **this is a bug**. However, I'd be happy to explain the reason. 

Firstly, according to the vid2vid paper, the expression "exp" in this work is indeed a deformation relative to a neutral expression. Secondly, the reason this work requires the first frame's expression to be a natural face is that, under the default inference settings, each frame of the driving video will be compared to the first frame (i.e., a diff calculation) and then added to the source frame's expression. See https://github.com/KwaiVGI/LivePortrait/blob/main/src/live_portrait_pipeline.py#L353

This means that if the first frame of the driving video has an open mouth while the source image does not, subsequent frames of the driving video that show a closing mouth action will cause the source image's originally closed mouth to purse even tighter, thus the mouth cannot open. 

Therefore, we expected that under these conditions, using the "--no_flag_relative_motion" option would allow us to bypass the difference calculation with the first frame and directly use the frame-by-frame exp from the driving video to guide the generation, in the inference code it did so, see https://github.com/KwaiVGI/LivePortrait/blob/main/src/live_portrait_pipeline.py#L362

This was an expected behavior, but in reality, the presence of the driving option (i2v) expression-friendly prevented this behavior from functioning correctly. I have provided some feedback on this issue and the author fixed that problem, see https://github.com/KwaiVGI/LivePortrait/pull/372/files

Of course, copying a natural frame to the beginning of the video can also solve this problem, but it is an **entirely unnecessary action**. Regarding the strange results caused by retargeting the lips, as I am on vacation today, I can only provide a brief text response. I can supplement this with some video results after 2 days. I hope my response is helpful.

**Comment by simplyexperimental** [comment]
@P2Oileen Hmm when I speak about having the first frame - this is for the driving video only.
For the target video you are right that it doesn't matter the expression as it will conform to the driving video.
But the relative checkbox is used to try to blend the target animation and driving video animations together while if you leave the checkbox unchecked it will try to mostly ignore the target video's expression and do a complete replace of the target expression with the driving video expression but again this is influenced by the first frame of driving neutral being better and as you observed if it's not neutral; open mouth then the persons lips will clamp for the reasons you mentioned.

Now when I clicked pose friendly or expression friendly they didn't change anything maybe this is the bug or are you saying that the bug is that we shouldn't need a first frame in the driving it should just work if just uncheck relative which I would say from my testing relative only decides to blend or replace the expressions of target and driving based on driving meaning the first frame of driving matters.

**Comment by P2Oileen** [comment]
@simplyexperimental Sorry, it was a bit tough to follow with all the long sentences and unclear references. I used ChatGPT to help me out, but I’m worried I might’ve misunderstood something. Could you do me a favor and break it down into simpler terms? It would be great if you could directly point out what exactly your problem is or something else.

**Comment by simplyexperimental** [comment]
@P2Oileen I said that the "relative motion" option decides between replacing or blending the facial animation but that you still need a proper first frame for the driving video otherwise I think the results will be bad.
You should make a first frame and see if that gives better or worse results for when "relative motion" is turned on or off.

This is how "relative motion" worked before the implementation of "expression friendly" and "pose friendly"options were added so I don't think it's a bug.

But since "expression friendly" and "pose friendly" don't do anything at all for me when I activate them you could still be right that the author wanted to change it so you don't need a good first frame so that's between you and the author to test.

**Comment by P2Oileen** [comment]
@simplyexperimental 
## Are the result the same?
You’re wondering about the differences in choosing different “driving option (i2v) xxx friendly” options **before fixing bugs** when relative motion is off. The answer is **NO**. I will explain these differences using some videos. 
Since the problem only occurs when the first frame of the driving video is in an open-mouth state, I chosed a driving video with open-mouth in the beginning.

1. For "expression friendly" and "relative motion **on**":

https://github.com/user-attachments/assets/ea93167b-9a63-4aa4-a9ff-96ff9599b7b4

Mouth in the generated video keep closed.

2. For "expression friendly" and "relative motion **off**":

https://github.com/user-attachments/assets/03ea4859-19b8-4c8c-a03e-090168a508d0

As I explained before, while relative motion is **off**, the mouth should be open and act exactly like the driving video. However due to the bug, it failed to do so.
> Therefore, we expected that under these conditions, using the "--no_flag_relative_motion" option would allow us to bypass the difference calculation with the first frame and directly use the frame-by-frame exp from the driving video to guide the generation, in the inference code it did so, see https://github.com/KwaiVGI/LivePortrait/blob/main/src/live_portrait_pipeline.py#L362
This was an expected behavior, but in reality, the presence of the driving option (i2v) expression-friendly prevented this behavior from functioning correctly.

3. For "pose friendly" and "relative motion **off**":

https://github.com/user-attachments/assets/2cf7af1e-291b-4458-b209-c46703c14111

Mouth motion in the generated video is good after changed driving option (i2v).

## Did the author add expression friendly to bypass the requirement of a good first frame of driving?
**No**.  Please check https://github.com/KwaiVGI/LivePortrait/blob/b01aeb4050d9a77486c478599b62aed7cd9eb5c6/assets/docs/changelog/2024-08-02.md?plain=1#L51 to get official explanation. Or you can directly check the code https://github.com/KwaiVGI/LivePortrait/blob/b01aeb4050d9a77486c478599b62aed7cd9eb5c6/src/live_portrait_pipeline.py#L389-L395. A simple but not rigorous explanation is(I recommend you to see the code), when the “expression-friendly” option is turned on, it suppresses the expression differences between generated frames and initial frame. 

## What the expression and pose friendly SUPPOSED to do?
Again, check https://github.com/KwaiVGI/LivePortrait/blob/b01aeb4050d9a77486c478599b62aed7cd9eb5c6/assets/docs/changelog/2024-08-02.md?plain=1#L51 to get official explanation.

## Retarget lips results
As I mentioned before, 
> Regarding the strange results caused by retargeting the lips, as I am on vacation today, I can only provide a brief text response. I can supplement this with some video results after 2 days.

This is the generated result using setting:
> flag_lip_retargeting: bool = True
flag_relative_motion: bool = False
flag_eye_retargeting: bool = False
@tonyabracadabra You can also have a look at this video and compare with the results shown in `3. For "pose friendly" and "relative motion **off**"`

https://github.com/user-attachments/assets/c6037b50-e007-4142-b02e-6a09d967f088

**Comment by P2Oileen** [comment]
It appears that the issue has been resolved, so I’m closing this issue.

**Comment by mhwu2017** [comment]
> @simplyexperimental
> 
> ## Are the result the same?
> You’re wondering about the differences in choosing different “driving option (i2v) xxx friendly” options **before fixing bugs** when relative motion is off. The answer is **NO, they are not the same**. I will explain these differences using some videos. Since the problem only occurs when the first frame of the driving video is in an open-mouth (or not in a neutral face) state, I chosed a driving video with open-mouth in the beginning.
> 
> 1. For "expression friendly" and "relative motion **on**":
> 
>  11_1725420449.mp4 
> Mouth in the generated video keep closed.
> 
> 2. For "expression friendly" and "relative motion **off**":
> 
>  13_1725420490.mp4 
> As I explained before, while relative motion is **off**, the mouth should be open and act exactly like the driving video. However due to the bug, it failed to do so.
> 
> > Therefore, we expected that under these conditions, using the "--no_flag_relative_motion" option would allow us to bypass the difference calculation with the first frame and directly use the frame-by-frame exp from the driving video to guide the generation, in the inference code it did so, see https://github.com/KwaiVGI/LivePortrait/blob/main/src/live_portrait_pipeline.py#L362
> > This was an expected behavior, but in reality, the presence of the driving option (i2v) expression-friendly prevented this behavior from functioning correctly.
> 
> 3. For "pose friendly" and "relative motion **off**":
> 
>  22_1725438239.mp4 
> Mouth motion in the generated video is good after changed driving option (i2v).
> 
> ## Did the author add expression friendly to bypass the requirement of a good first frame of driving?
> **No**. Please check
> 
> https://github.com/KwaiVGI/LivePortrait/blob/b01aeb4050d9a77486c478599b62aed7cd9eb5c6/assets/docs/changelog/2024-08-02.md?plain=1#L51
> 
> to get official explanation. Or you can directly check the code
> https://github.com/KwaiVGI/LivePortrait/blob/b01aeb4050d9a77486c478599b62aed7cd9eb5c6/src/live_portrait_pipeline.py#L389-L395
> 
> . A simple but not rigorous explanation is(I recommend you to see the code), when the “expression-friendly” option is turned on, it suppresses the expression differences between generated frames and initial frame.
> ## What the expression and pose friendly SUPPOSED to do?
> Again, check
> 
> https://github.com/KwaiVGI/LivePortrait/blob/b01aeb4050d9a77486c478599b62aed7cd9eb5c6/assets/docs/changelog/2024-08-02.md?plain=1#L51
> 
> to get official explanation.
> ## Retarget lips results
> As I mentioned before,
> 
> > Regarding the strange results caused by retargeting the lips, as I am on vacation today, I can only provide a brief text response. I can supplement this with some video results after 2 days.
> 
> This is the generated result using setting:
> 
> > flag_lip_retargeting: bool = True
> > flag_relative_motion: bool = False
> > flag_eye_retargeting: bool = False
> 
> @tonyabracadabra You can also have a look at this video and compare with the results shown in `3. For "pose friendly" and "relative motion **off**"`
> 
>  15_1725420646.mp4

Sorry, but when I use the same option as you, "no_flag_relative_motion" "driving_option=pose-friendly", I still got the problem of lip close when the first frame is open-mouth, do you change other options?

**Comment by mhwu2017** [comment]
> It appears that the issue has been resolved, so I’m closing this issue.

Sorry, but when I use the same option as you, "no_flag_relative_motion" "driving_option=pose-friendly", I still got the problem of lip close when the first frame of the driving video is open-mouth, do you change other options?

**Comment by joytsay** [comment]
i can confirm that with 
`--driving-option pose-friendly --no-flag-relative-motion`
the driving landmarks re-targeting produce far better results

**Comment by mhwu2017** [comment]
> i can confirm that with `--no-flag-relative-motion` re-targeting is more true to driving landmarks

have you tried to use `--no-flag-relative-motion --animation_region=exp` ？ When I use these two options at the same time, the results become very strange, especially the lips.

**Comment by armynew** [comment]
The feeling of not being able to open the mouth or opening very little, pursing the mouth and talking, how to deal with this? thank you @cleardusk
