### ISSUE TITLE
Flask等框架来创建一个API来处理这个任务, create an API to handle this task,

### ISSUE THREAD

**Issue by huanggou666** [KwaiVGI/LivePortrait#38]
步骤 1：安装Flask
首先，你需要安装Flask。可以通过pip来安装：
pip install Flask
步骤 2：创建Flask应用
创建一个新的Python脚本，例如app1.py，并添加以下代码：
 `from flask import Flask, request, jsonify
import subprocess
import os

app = Flask(__name__)

@app.route('/run-inference', methods=['POST'])
def run_inference():
    # 获取JSON请求中的数据
    data = request.json
    source_image = data.get('source_image')
    driving_video = data.get('driving_video')
    
    if not source_image or not driving_video:
        return jsonify({"error": "Missing source_image or driving_video parameter"}), 400
    
    # 构建命令
    command = f'python inference.py -s {source_image} -d {driving_video}'
    
    # 运行命令
    try:
        subprocess.run(command, check=True, shell=True, cwd='C:/ALLWEBUI/liveportarit/LivePortrait')
        return jsonify({"message": "Inference completed successfully"}), 200
    except subprocess.CalledProcessError as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
`
步骤 3：运行Flask应用
在终端中运行Flask应用：
`python app1.py
`

步骤 4：通过API调用
现在，你可以通过API来调用这个命令。例如，使用curl命令：
`import requests

url = 'http://localhost:5000/run-inference'
data = {
    'source_image': 'Your image file here',
    'driving_video': 'assets/examples/driving/d13(1).mp4'
}

response = requests.post(url, json=data)

print(response.json())
`

**Comment by Rizwanali324** [comment]
Does this api (infernace.py file) add the audio in results.  as for now im not getting any audio ..
how can i handle this ?
