### ISSUE TITLE
[solution]pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>

### ISSUE THREAD

**Issue by emboss33** [KwaiVGI/LivePortrait#387]
when you got  this error while animate process on webui 

`pip uninstall fastapi`

i just added this line and 

run this command on my anaconda env 

put this line on existing requirements.txt

`fastapi<0.113.0`

and run 

`pip install -r  requirements.txt`

and then the problem is gone 

refer this

https://github.com/gradio-app/gradio/pull/9277

**Comment by emboss33** [comment]
my result of pip freeze
aiofiles==23.2.1
albucore==0.0.15
albumentations==1.4.10
altair==5.4.1
annotated-types==0.7.0
anyio==4.4.0
attrs==24.2.0
certifi==2024.8.30
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
coloredlogs==15.0.1
contourpy==1.3.0
cycler==0.12.1
docstring_parser==0.16
eval_type_backport==0.2.0
exceptiongroup==1.2.2
fastapi==0.112.4
ffmpeg-python==0.2.0
ffmpy==0.4.0
filelock==3.13.1
flatbuffers==24.3.25
fonttools==4.53.1
fsspec==2024.2.0
future==1.0.0
gradio==4.37.1
gradio_client==1.0.2
h11==0.14.0
httpcore==1.0.5
httpx==0.27.2
huggingface-hub==0.24.6
humanfriendly==10.0
idna==3.8
imageio==2.34.2
imageio-ffmpeg==0.5.1
importlib_resources==6.4.5
intel-openmp==2021.4.0
Jinja2==3.1.3
joblib==1.4.2
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
kiwisolver==1.4.7
lazy_loader==0.4
lmdb==1.4.1
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.0
mdurl==0.1.2
mkl==2021.4.0
mpmath==1.3.0
narwhals==1.7.0
networkx==3.2.1
numpy==1.26.4
onnx==1.16.1
onnxruntime-gpu==1.18.0
opencv-python==4.10.0.84
opencv-python-headless==4.10.0.84
orjson==3.10.7
packaging==24.1
pandas==2.2.2
pillow==10.2.0
protobuf==5.28.1
pydantic==2.9.1
pydantic_core==2.23.3
pydub==0.25.1
Pygments==2.18.0
pykalman==0.9.7
pyparsing==3.1.4
pyreadline3==3.4.3
python-dateutil==2.9.0.post0
python-multipart==0.0.9
pytz==2024.2
PyYAML==6.0.1
referencing==0.35.1
regex==2024.9.11
requests==2.32.3
rich==13.7.1
rpds-py==0.20.0
ruff==0.6.4
scikit-image==0.24.0
scikit-learn==1.5.2
scipy==1.13.1
semantic-version==2.10.0
shellingham==1.5.4
shtab==1.7.1
six==1.16.0
sniffio==1.3.1
starlette==0.38.5
sympy==1.12
tbb==2021.11.0
threadpoolctl==3.5.0
tifffile==2024.8.30
tokenizers==0.12.1
tomlkit==0.12.0
torch==2.3.0+cu118
torchaudio==2.3.0+cu118
torchvision==0.18.0+cu118
tqdm==4.66.4
transformers==4.22.0
typer==0.12.5
typing_extensions==4.12.2
tyro==0.8.5
tzdata==2024.1
urllib3==2.2.2
uvicorn==0.30.6
websockets==11.0.3
zipp==3.20.1

**Comment by k12795g** [comment]
thx, it really help me

**Comment by kittinan** [comment]
Thanks save my time

**Comment by Misty1113** [comment]
It works. Thank you very much.
