### ISSUE TITLE
 GTX 1660 Ti生成的视频头像部分黑屏

### ISSUE THREAD

**Issue by ItsSecrets** [KwaiVGI/LivePortrait#40]
NVIDIA GeForce GTX 1660 Ti 跑出来的是这样的，是啥情况

![result](https://github.com/KwaiVGI/LivePortrait/assets/13164632/dfe26c78-329b-42d4-a958-1cecd4dddbf7)
![result2](https://github.com/KwaiVGI/LivePortrait/assets/13164632/fd515070-b168-421f-bb11-5bf80717c0a1)

**Comment by zzzweakman** [comment]
You can try turning off half precision inference, refer to #48 @ItsSecrets
