### ISSUE TITLE
v2v的时候最后总时长会缩短，最终导致音画不同步

### ISSUE THREAD

**Issue by wangqiaoch** [KwaiVGI/LivePortrait#402]
my source video is 1min，driving video is 26s，but the animated video is 20s，why？
我用一个任意长度的source video（比driving video长），同时用一个固定的26s的driving video，但是生成的视频却是20s的，同时能看出来是嘴型是加速了的，但是声音还是原速，导致最后音画不同步，并且声音也被截断了。为什么会这样呢？
btw：在这里生成的时候是正常的：https://huggingface.co/spaces/fffiloni/liveportrait-vid2vid

**Comment by dddwhy** [comment]
+1

**Comment by yulj21** [comment]
检查下你输入视频fps

**Comment by wangqiaoch** [comment]
> 检查下你输入视频fps

请问fps应该是多少才不会有这个情况呀，30？

**Comment by wangqiaoch** [comment]
> > 检查下你输入视频fps
> 
> 请问fps应该是多少才不会有这个情况呀，30？

找到问题了，source video 比 driving video 的帧率高就会出这个问题
