### ISSUE TITLE
Are there any updates planned?

### ISSUE THREAD

**Issue by videocringe** [KwaiVGI/LivePortrait#412]
It’s as if many more different functions could be introduced into this project, but we haven’t heard anything from the authors for a month now

**Comment by cleardusk** [comment]
@videocringe 
Good question! A lot of common features have already been implemented by community developers, and there are many secondary application examples on X (just search for ‘liveportrait’). So the LivePortrait team is also thinking about what to focus on next. Also, some of our team members are currently busy with graduation and job hunting, so there might be a bit of a gap in updates.

**Comment by videocringe** [comment]
Thank you for your answer, I look forward to hearing from you!
