### ISSUE TITLE
When we enable eye retarget ratio the movement is  gone

### ISSUE THREAD

**Issue by FurkanGozukara** [KwaiVGI/LivePortrait#45]
I am working on a 1-click installers (all ready for Windows, RunPod, Massed Compute & Kaggle (works amazing on free Kaggle account)) and a tutorial video and **flag_eye_retargeting is not working**

I have made a lot of changes and implemented the logic but here comparison

Default settings as below

https://github.com/KwaiVGI/LivePortrait/assets/19240467/398f36c9-5f71-4593-a011-0611a15ae157

When target eyes-open ratio is 30% more of original and target lip-open ratio is 80% more as below

https://github.com/KwaiVGI/LivePortrait/assets/19240467/6276ca7c-87cb-4027-a95e-cd460af24ace

![screencapture-127-0-0-1-7860-2024-07-06-20_10_43](https://github.com/KwaiVGI/LivePortrait/assets/19240467/29850709-8c9a-4e90-92c9-68fb207b6938)

**Comment by thewayur** [comment]
Hi, from where i can change the eye, mouth ratios for animation? from retargeting? because it is ineffective in my case and only working for img (retargeting section)

I have installed it in my localhost. Only these three checks are effecting generated animations  = relative motion, do crop and paste-reback

Also i am not seeing any readable docs here, am i missing something?

**Comment by FurkanGozukara** [comment]
> Hi, from where i can change the eye, mouth ratios for animation? from retargeting? because it is ineffective in my case and only working for img (retargeting section)
> 
> I have installed it in my localhost. Only these three checks are effecting generated animations = relative motion, do crop and paste-reback
> 
> Also i am not seeing any readable docs here, am i missing something?

this is my custom development

currently it is not supported in this repo. i am preparing a tutorial for my development

**Comment by thewayur** [comment]
@FurkanGozukara oh i see, great development. Any small guide from your experiences will help me a lot🙏

Best  wishes😊

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara oh i see, great development. Any small guide from your experiences will help me a lot🙏
> 
> Best wishes😊

ty
