### ISSUE TITLE
An alternative project EchoMimicV2 is open-sourced

### ISSUE THREAD

**Issue by lymhust** [KwaiVGI/LivePortrait#450]
EchoMimicV2 utilizes a reference image, an audio clip, and a sequence of hand pose to generate a high-quality animation video,
ensuring coherence between audio content and half-body movements.
Project Page: https://antgroup.github.io/ai/echomimic_v2/
GitHub Page: https://github.com/antgroup/echomimic_v2

https://github.com/user-attachments/assets/abb7d22f-9287-402e-be80-6bac2fe5f530

https://github.com/user-attachments/assets/473e9847-20b7-4cdd-ac10-6203669d7228

**Comment by cleardusk** [comment]
Your work is great, but this issue is unrelated to the discussion, so closed.
