### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED in logs

### ISSUE THREAD

**Issue by jonk999** [KwaiVGI/LivePortrait#47]
I am getting the following when performing an animate. I have done a 'git pull' to make sure I have latest files and re-ran 'pip install -r requirements.txt' after doing so.

```
I:\zzzz_stablediffusion-other\zz_LP\LivePortrait\venv\lib\site-packages\torch\nn
\modules\conv.py:605: UserWarning: Plan failed with a cudnnException:
CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed
cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at
..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return F.conv3d(
I:\zzzz_stablediffusion-other\zz_LP\LivePortrait\venv\lib\site-packages\torch\nn
\modules\conv.py:456: UserWarning: Plan failed with a cudnnException:
CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed
cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at
..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
Animating... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:29
Concatenating result... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Dump to animations/s10--d5_concat.mp4

writing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--[swscaler @ 000001adabad0000] Warning: data is not aligned! This can lead to a speed loss
Dump to animations/s10--d5.mp4
```

**Comment by kigner** [comment]
torch.backends.cudnn.benchmark = True

**Comment by oisilener1982** [comment]
Is there a video tutorial how to do this?

To set torch.backends.cudnn.benchmark to True in PyTorch, you can simply include the following line of code in your script or notebook:

Python
import torch
torch.backends.cudnn.benchmark = True

**Comment by FurkanGozukara** [comment]
I am preparing 1 tutorial right now but not ready yet sadly. 1 click to install and use

https://github.com/KwaiVGI/LivePortrait/assets/19240467/deed8be1-8556-4769-80cc-e46ea57f74ca

**Comment by zzzweakman** [comment]
> Is there a video tutorial how to do this?
> 
> To set torch.backends.cudnn.benchmark to True in PyTorch, you can simply include the following line of code in your script or notebook:
> 
> Python import torch torch.backends.cudnn.benchmark = True

Our official tutorial is already on the schedule:). Stay tuned!
