### ISSUE TITLE
做了款解压即用的Windows工具，不用搭建环境

### ISSUE THREAD

**Issue by zhaoyun0071** [KwaiVGI/LivePortrait#48]
伟大的工作，效果很好。
https://github.com/zhaoyun0071/LivePortrait-windows-GUI

**V1.2 版本：2024-7-7**
1、现在驱动视频支持自动裁剪人脸区域了，默认勾选自动裁剪视频人脸区域即可；

2、修复16代显卡黑图的问题，不勾选半精度即可；

3、生成的视频和驱动视频帧率抱持一致，且带有驱动视频的声音；

4、支持pkl格式的驱动视频导入，pkl格式就是勾选自动裁剪视频人脸区域后自动生成的数据文件，和驱动视频同名同目录。

**V1.1 版本：2024-7-5**

1、支持批量选择图片和驱动视频。批量生成。

**V1.0 版本：2024-7-4**

1、基于LivePortrait项目，原汁原味，支持图片模拟驱动视频的表情、五官动作等。

**Comment by zzzweakman** [comment]
老铁牛逼！ @zhaoyun0071

**Comment by zhaowei0315** [comment]
V587
