### ISSUE TITLE
Demo Reproduce

### ISSUE THREAD

**Issue by wangzheng1209** [KwaiVGI/LivePortrait#5]
Great Work!!! Could you give more instructions on how to reproduce the demos in the project page.

**Comment by cleardusk** [comment]
Except for editing and animals part, other demos can be repreduced.

**Comment by wangzheng1209** [comment]
Thanks for you reply.  I can reproduce the demos except for editing and animals part. 
Do you consider to release the code of editing and animal part?  And for animal part, do you consider to release the data?
