### ISSUE TITLE
Gradio Colab Help

### ISSUE THREAD

**Issue by TheLocalLab** [KwaiVGI/LivePortrait#50]
I'm trying to create a colab notebook for the gradio version of the project. I have all the pieces together but for some reason when I run the final cell "python app.py" , the cell seem to get stuck and doesn't execute the rest of the script. No error pops up but a Gradio link never generates. Would anyone happen to have an idea what might cause this. Any help would be appreciated. Link to the colab - https://colab.research.google.com/drive/15pX7d8FfCMTty1v0DpgeApIR4VCduyDR?usp=sharing

**Comment by FurkanGozukara** [comment]
google colab banned gradio share for free users - if you are trying on free account

i made a kaggle notebook for free users and hopefully a video will be published

https://github.com/KwaiVGI/LivePortrait/assets/19240467/5d38dd50-accc-4e26-99a2-75a89ac9dcfb

**Comment by bulieme** [comment]
> google colab banned gradio share for free users - if you are trying on free account
> 
> i made a kaggle notebook for free users and hopefully a video will be published
> 
>  output_720p.mp4

it doesnt get banned, they have changed the TOS

**Comment by FurkanGozukara** [comment]
> > google colab banned gradio share for free users - if you are trying on free account
> > i made a kaggle notebook for free users and hopefully a video will be published
> > output_720p.mp4
> 
> it doesnt get banned, they have changed the TOS

if you have a free colab account when you use gradio live share your session will be auto terminated

however i made a free kaggle notebook with a special way

this special way doesnt work on colab but works on kaggle for gradio apps

https://github.com/KwaiVGI/LivePortrait/issues/78

**https://youtu.be/wG7oPp01COg**

### [**LivePortrait: No-GPU Cloud Tutorial - RunPod, MassedCompute & Free Kaggle Account - Animate Images**](https://youtu.be/wG7oPp01COg)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/fvWxGLUrIe5XWqP37OBfU.png)](https://youtu.be/wG7oPp01COg)

**Comment by NeuralFalconYT** [comment]
Check Out This one it's working:
https://github.com/NeuralFalconYT/LivePortrait-Colab

**Comment by TheLocalLab** [comment]
> Check this one out, it's working: https://github.com/NeuralFalconYT/LivePortrait-Colab

amazing, thanks!
