### ISSUE TITLE
Turn off head motion option

### ISSUE THREAD

**Issue by BarnabasTakacs** [KwaiVGI/LivePortrait#51]
Excellent work, congratulations!

I wonder if there is an option to remove the head motion completely. In my test I was driving it with a series of still 
 images and the head started shaking and changing its size.

Thanks in advance

**Comment by FurkanGozukara** [comment]
yes it is possible with enabling Target Eye Lip Open Ratio

you need to check out source code to make it enabled - in config files

i added that feature to my gradio app

![screencapture-127-0-0-1-7860-2024-07-07-19_12_38](https://github.com/KwaiVGI/LivePortrait/assets/19240467/30469b13-86a8-4356-adec-5553e7249daa)

**Comment by BarnabasTakacs** [comment]
Thank you very much for the detailed responses, I will have a look and get back to you.
