### ISSUE TITLE
🐱🐶 Generalization to Animals 🐼🐱

### ISSUE THREAD

**Issue by juntaosun** [KwaiVGI/LivePortrait#53]
🐱🐶 Generalization to Animals 🐼🐱
By fine-tuning on animals data, these cute cats, dogs and pandas can be precisely driven by humans

![image](https://github.com/KwaiVGI/LivePortrait/assets/22288197/a5d79183-6597-49be-bb80-d3067f0a3580)
-----------------------------

I'm interested in the animal models, but I tried the current code and it says no faces were found. Can you update the animal/pet code to support that? Thanks

**Comment by Green-li** [comment]
Mark

**Comment by oisilener1982** [comment]
I also need this one

**Comment by okideal** [comment]
M

**Comment by dwgeneral** [comment]
Mark

**Comment by vcen** [comment]
I need this too. How do I make it?

**Comment by willehlad** [comment]
me too thanks

**Comment by franz101** [comment]
Me three

**Comment by Inferencer** [comment]
https://github.com/KwaiVGI/LivePortrait/assets/121839197/0be54296-09aa-4838-bc32-d5f628148376

**Comment by ZeroCool22** [comment]
> large-Capuchin-Monkey-photo--d6_trim.mp4

![2b63f580cd3ed1c9a9ea3cfdf3da5cb4](https://github.com/KwaiVGI/LivePortrait/assets/13344308/3c174fb9-7b3d-4749-8ce6-d0d502c73537)

**Comment by chaochao0** [comment]
M

**Comment by cleardusk** [comment]
So funny of this case 😄 @Inferencer Could you please provide the original input portrait : )

> large-Capuchin-Monkey-photo--d6_trim.mp4

**Comment by Inferencer** [comment]
> So funny of this case 😄 @Inferencer Could you please provide the original input portrait : )
> 
> > large-Capuchin-Monkey-photo--d6_trim.mp4


https://github.com/KwaiVGI/LivePortrait/assets/121839197/9cddaf69-ec54-46e1-a5df-7e7e886c63fb

**Comment by cleardusk** [comment]
Great thanks! @Inferencer

**Comment by cleardusk** [comment]
Is this picture licensed? @Inferencer I think it's a good case and is suitable as the default input case in HF space 😄

**Comment by Inferencer** [comment]
> Is this picture licensed? @Inferencer I think it's a good case and is suitable as the default input case in HF space 😄

it's copyrighted _@Edwin Butter / Shutterstock_ I found it on worldwildlife.org from an image search, I have been testing on various animals, it works on most monkeys including those from the planet of the apes films. You will notice however the human teeth in the result, would be interested to see how it performs with an open mouth showing fangs on the current model.

**Comment by franz101** [comment]
@Inferencer loved your example, I love monkeys, but tried running it with cats and it would not recognize the face. Temporary tried this one:
https://github.com/MarQuisCheshire/Pets-Face-Recognition

for detection

**Comment by Inferencer** [comment]
> @Inferencer loved your example, I love monkeys, but tried running it with cats and it would not recognize the face. Temporary tried this one: https://github.com/MarQuisCheshire/Pets-Face-Recognition
> 
> for detection

Monkeys are closer to humans even with a different face detection you will be a slave to the limits of the model, This model was extensively trained and can handle a huge amount as you may know but even some monkey pictures may not work 
I did some recent tests with a "Slow Loris" and it seemed to also perform well 

https://github.com/user-attachments/assets/6eb43bfb-9032-4020-bcb5-46c796fd3ca6

![SlowLoris](https://github.com/user-attachments/assets/4cf990e8-e840-436e-8131-5b483652d445)

**Comment by cleardusk** [comment]
> worldwildlife.org

I use the monkey as the default showcase on HF Space😀. If there are any copyright issues, I will take it down immediately. : )

**Comment by cleardusk** [comment]
Refer to the updates: https://github.com/KwaiVGI/LivePortrait/blob/main/assets/docs/changelog/2024-08-02.md

**Comment by stevanisya** [comment]
Hello, 
anybody found a solution for liveportrait for cats or dogs ? 
thank you !!

**Comment by EmmaThompson123** [comment]
@cleardusk I want to finetune the animal generator model, my key issue is the animal model still use human dirving video in inference stage, but in training stage, can we use the animal image as driving, or if still use the human image as driving, how can we get the paired source animal image, driving human image and target animal image ?
