### ISSUE TITLE
eyes appear less open when enable eye retarget

### ISSUE THREAD

**Issue by Vincent-luo** [KwaiVGI/LivePortrait#58]
Using eye retarget reduces the issue of closing eyes, but the eyes appear less open in the generated images. The comparison below shows the first frame of the video. Is there a way to fix this?
<img width="1438" alt="image" src="https://github.com/KwaiVGI/LivePortrait/assets/62138655/aa6ca51c-2539-4acf-a739-65078c3e3151">

**Comment by Vincent-luo** [comment]
I'm experimenting with the source code instead of ComfyUI. Should I use a value greater than 1 or less than 1? I tried modifying the code to add a scale to eye retargeting, but it doesn't seem to work very well.

**Comment by kijai** [comment]
1.0 is the default, higher value should open them more, I think it only works with the eye_retargeting/relative mode though, here's an example with value of around 2.0:

https://github.com/KwaiVGI/LivePortrait/assets/40791699/c43f6844-aa64-459a-94cb-cfb3000c0ab1

**Comment by kijai** [comment]
I simply added a multiplier here:
![image](https://github.com/KwaiVGI/LivePortrait/assets/40791699/39da70f8-a01d-408b-821a-5d5bbd100c9f)

**Comment by Vincent-luo** [comment]
@kijai Oh, I found something interesting! 
Directly rescaling `combined_eye_ratio_tensor` doesn't work well for me. Considering `combined_eye_ratio_tensor` is a concatenation of source eyes-open condition `c_s,eyes` and driving eyes-open scalar `c_d,eyes`, I think we only need to rescale `c_d,eyes` instead of rescale both. So I add a multiplier here:
<img width="981" alt="image" src="https://github.com/KwaiVGI/LivePortrait/assets/62138655/569cc7b7-c20e-48bd-8b5b-ac1b23b6c6b2">

The following are some generated videos with different multipliers, the results seem very good. With higher values, eyes open more.

multiplier=0.8
https://github.com/KwaiVGI/LivePortrait/assets/62138655/30c60f88-e634-4661-be04-3b1a6b7c8d3d

multiplier=1.2
https://github.com/KwaiVGI/LivePortrait/assets/62138655/f8c0f39d-3fe3-4b42-a2bc-540b2f6f2434

multiplier=1.4
https://github.com/KwaiVGI/LivePortrait/assets/62138655/bafd4d0e-2178-48a7-9925-0eba6426b932

**Comment by Vincent-luo** [comment]
multiplier=0.8
<img width="1437" alt="image" src="https://github.com/KwaiVGI/LivePortrait/assets/62138655/40361026-4411-46e1-890a-2081934ec880">
multiplier=1.2
<img width="1440" alt="image" src="https://github.com/KwaiVGI/LivePortrait/assets/62138655/3b959c72-fd22-4784-b846-ee336601c033">
multiplier=1.4
<img width="1440" alt="image" src="https://github.com/KwaiVGI/LivePortrait/assets/62138655/aa9ba695-73c1-4d57-9c07-b1e0ba9bc671">

**Comment by FurkanGozukara** [comment]
> 1.0 is the default, higher value should open them more, I think it only works with the eye_retargeting/relative mode though, here's an example with value of around 2.0:
> 
>  LivePortrait_00003.2.mp4

i added multipler to your 

> 1.0 is the default, higher value should open them more, I think it only works with the eye_retargeting/relative mode though, here's an example with value of around 2.0:
> 
>  LivePortrait_00003.2.mp4

when i enable eye retarget ratio my head movement is lost

how is yours moving? https://github.com/KwaiVGI/LivePortrait/issues/45

**Comment by Vincent-luo** [comment]
Yes, when enabling retarget the head movement is gone XD

**Comment by FurkanGozukara** [comment]
> Yes, when enabling retarget the head movement is gone XD

did you find how to fix this issue?

**Comment by Vincent-luo** [comment]
> did you find how to fix this issue?

When enabling retarget and disabling relative pose, you can get head movement, but I don't know if it's the best solution.

**Comment by FurkanGozukara** [comment]
> > did you find how to fix this issue?
> 
> When enabling retarget and disabling relative pose, you can get head movement, but I don't know if it's the best solution.

thanks yes it works but results not great


https://github.com/KwaiVGI/LivePortrait/assets/19240467/6165b1df-11a1-48bb-8b7e-16b94c38ab73


https://github.com/KwaiVGI/LivePortrait/assets/19240467/d3032aad-a3a9-45b3-b01f-a7386f38aff0

**Comment by Vincent-luo** [comment]
the results might be better if the driving image and the source image have similar head poses.

**Comment by FurkanGozukara** [comment]
> the results might be better if the driving image and the source image have similar head poses.

yep looks like the case

**Comment by multilogin7** [comment]
> I simply added a multiplier here: ![image](https://github.com/KwaiVGI/LivePortrait/assets/40791699/39da70f8-a01d-408b-821a-5d5bbd100c9f)

Hello. Where exactly did you add the multiplier? Thank you.

**Comment by multilogin7** [comment]
> [@kijai](https://github.com/kijai) О, я нашел кое-что интересное! Непосредственный перемасштабирование `combined_eye_ratio_tensor`Не очень хорошо для меня. Учитывая `combined_eye_ratio_tensor`является констатацией источника глаз-открытого состояния `c_s,eyes`и вождение глаза-открытые скалярия `c_d,eyes`, я думаю, нам нужно только переделать `c_d,eyes`Вместо того, чтобы перемасштабировать оба. Итак, я добавляю множитель здесь: <img alt="изображение" width="981" src="https://private-user-images.githubusercontent.com/62138655/346608784-569cc7b7-c20e-48bd-8b5b-ac1b23b6c6b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIxMTc0MzAsIm5iZiI6MTc0MjExNzEzMCwicGF0aCI6Ii82MjEzODY1NS8zNDY2MDg3ODQtNTY5Y2M3YjctYzIwZS00OGJkLThiNWItYWMxYjIzYjZjNmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzE2VDA5MjUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczN2JhMTcxODZjMjNjNjE5MDJlOTgyMDRiMmIxMGZiNjNkMDdjZDE4MzczOGQ2MmU2MzllMjBkOWQyMzQ5ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.smzi0CKhfN8s4HFAGlgJeHqWp-2RL7iCaTfg1i9elDs">
> 
> Ниже приведены некоторые сгенерированные видео с различными множителями, результаты кажутся очень хорошими. С более высокими ценностями глаза открываются больше.
> 
> мультипликатор=0.8
> s7--------конкат_0.8.mp4
> 
> множитель=1.2
> s7--------контакт_1.2.mp4
> 
> мультипликатор=1,4
> s7---d7_concat_1.4.mp4

Hello. Where exactly did you add the multiplier? Thank you.
