### ISSUE TITLE
✨Processing result feedback！✨

### ISSUE THREAD

**Issue by juntaosun** [KwaiVGI/LivePortrait#59]
The processing speed is fast and the effect is excellent. Thanks to Kuaishou for such a great team and such a high-quality project.

Tips for use: 
The first frame of the target video must be consistent with the face and angle of the source image, otherwise the subsequent frames will be confused. I don’t know how to optimize the automatic alignment function.

**Comment by AlonDan** [comment]
Looks great!
Can you please explain how to use VIDEO as a source?

I've tried it via the gradio app but it only allow Images.

**Comment by Inferencer** [comment]
> The processing speed is fast and the effect is excellent. Thanks to Kuaishou for such a great team and such a high-quality project.
> LivePortrait.mp4
> 
> Tips for use: The first frame of the target video must be consistent with the face and angle of the source image, otherwise the subsequent frames will be confused. I don’t know how to optimize the automatic alignment function.

throw up a quick tut

**Comment by xpeng** [comment]
great work! how to do this with video as source?

**Comment by huanggou666** [comment]
> great work! how to do this with video as source? you mentioned "the automatic alignment function", could you please clarify how to do this, thanks

the driving video only have one frame ,each frame is a driving video ,  input image is each frame of the target video I guess , then do it in batch, then stitch the result back together

**Comment by guoguang002** [comment]
视频是怎么实现的

**Comment by AlonDan** [comment]
For VIDEO I drag and drop **PNG sequence** (via multiple files from video) for example:
0001.png - 0099.png but when pressing Animate, it only animates the first frame.

So I wonder how did you manage to use VIDEO as a source via the Gradio App?
If anyone knows how to do that, please share 🙏

**Comment by seinfinity** [comment]
> For VIDEO I drag and drop **PNG sequence** (via multiple files from video) to the Source Portrait, for example: 0001.png - 0099.png but when pressing Animate, it only animates the first frame.
> 
> So I wonder how did you manage to use VIDEO as a source via the Gradio App? If anyone knows how to do that, please share 🙏

same problem ,,!!
