### ISSUE TITLE
Can Release your training code?

### ISSUE THREAD

**Issue by songyang86** [KwaiVGI/LivePortrait#60]

**Comment by min-star** [comment]
amazing work!It's fast and the result is very well!
looking forward the training code,it is very worth to be learned!Some recent works are almost all based on diffusion model!

**Comment by Mrkomiljon** [comment]
Is it possible to use in realtime?

**Comment by zzzweakman** [comment]
> Is it possible to use in realtime?

Yes, you can find more details [here](https://github.com/warmshao/FasterLivePortrait). 😊

**Comment by zzzweakman** [comment]
We are sorry for not being able to release the training code due to internal restrictions. 😔 @songyang86
