### ISSUE TITLE
Black box

### ISSUE THREAD

**Issue by kelway74** [KwaiVGI/LivePortrait#62]
Hi - I've tried various combos, but I always get a black box on top of the face after the animation. Any suggestions? I'm using a jpg headshot and various of the example driving videos... thanks

![image](https://github.com/KwaiVGI/LivePortrait/assets/12819735/bbe8efcc-d1d5-4c32-8463-2307e34170bc)

**Comment by zzzweakman** [comment]
It is possible that your GPU is an older version. You might want to try disabling half-precision inference. Please refer to #40. @kelway74

**Comment by Yanxueyu** [comment]
Disabling half-precision is in here
inference_config.py  ->     flag_use_half_precision: bool = True # whether to use half precision

**Comment by kelway74** [comment]
Brilliant - it worked. Thanks so much.
