### ISSUE TITLE
great results feedback👍

### ISSUE THREAD

**Issue by shaoguowen** [KwaiVGI/LivePortrait#64]
thanks for your share! the processing is very fast and the result is so great!

https://github.com/KwaiVGI/LivePortrait/assets/57278682/b141a1d8-0c70-4a8e-82f3-8073a8315765

更多AIGC结果可以看我的视频号(温少的AIGC），欢迎讨论交流～

**Comment by velivaneski** [comment]
How did you could input the video?

**Comment by zzzweakman** [comment]
Thank you. Hope you enjoy it:)! @shaoguowen

**Comment by shaoguowen** [comment]
> How did you could input the video?

The upper right corner of the result video is the input video

**Comment by shaoguowen** [comment]
测试唱歌的视频，虽然后面有点抖，但整体的效果还是不错的

https://github.com/KwaiVGI/LivePortrait/assets/57278682/b62c154e-1d95-4338-878e-c985c5414db5

**Comment by guoguang002** [comment]
can videos and animals be used? I can only use photos

**Comment by shaoguowen** [comment]
> LivePortrait2.mp4

cool

**Comment by shaoguowen** [comment]
> can videos and animals be used? I can only use photos

The animal model seems to have not been released yet? You need to finetune it yourself as mentioned in issues

**Comment by ShiJiaying** [comment]
> can videos and animals be used? I can only use photos

See #119 for animal using released weight
