### ISSUE TITLE
Batch process

### ISSUE THREAD

**Issue by jaco001** [KwaiVGI/LivePortrait#68]
Good work!

How I can solve this scenario in batch file?
-input folder with jpg/png for source images (eg. from mp4)
-input folder with  jpg/png for drive images (eg. from mp4 too)
-output folder with jpg/png

This should take images one by one and process it like eg.
source001.png + drive001.png -> output001.png
source002.png + drive002.png -> output002.png
...

Any idea?
This code only inport/output mp4?

**Comment by zzzweakman** [comment]
Thank you for your attention! You can create a simple script (many LLMs can handle this task) to replace the `-s` and `-d` parameters in the `inference.py` script each time. @jaco001

**Comment by RikvdReijen** [comment]
Hey Jaco! Did you manage to write a working script (and could share it with us ;)

**Comment by jaco001** [comment]
You have now v2v https://github.com/KwaiVGI/LivePortrait/blob/main/assets/docs/changelog/2024-07-19.md 
So no need to change video to images as I want to do...
