### ISSUE TITLE
The error encountered when deploying the project to Google Cloud Platform.

### ISSUE THREAD

**Issue by SGneil** [KwaiVGI/LivePortrait#69]
I encountered the following error message when deploying the project to GCP. I followed the deployment process in the README, installed everything as instructed, and downloaded the pretrained weights.

When I execute this instruction, python inference.py

Error message 
Traceback (most recent call last):
  File "/home/neil47111202/test/LivePortrait/inference.py", line 33, in <module>
    main()
  File "/home/neil47111202/test/LivePortrait/inference.py", line 23, in main
    live_portrait_pipeline = LivePortraitPipeline(
  File "/home/neil47111202/test/LivePortrait/src/live_portrait_pipeline.py", line 38, in __init__
    self.live_portrait_wrapper: LivePortraitWrapper = LivePortraitWrapper(cfg=inference_cfg)
  File "/home/neil47111202/test/LivePortrait/src/live_portrait_wrapper.py", line 29, in __init__
    self.appearance_feature_extractor = load_model(cfg.checkpoint_F, model_config, cfg.device_id, 'appearance_feature_extractor')
  File "/home/neil47111202/test/LivePortrait/src/utils/helper.py", line 134, in load_model
    model.load_state_dict(torch.load(ckpt_path, map_location=lambda storage, loc: storage))
  File "/home/neil47111202/anaconda3/envs/.LivePortrait/lib/python3.9/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/neil47111202/anaconda3/envs/.LivePortrait/lib/python3.9/site-packages/torch/serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by lafitteee** [comment]
I encountered the same error. How did you fix it?

**Comment by meetbryce** [comment]
I'm running into this locally, too

**Comment by FurkanGozukara** [comment]
I have tutorial for cloud for who can't run

https://m.youtube.com/watch?v=wG7oPp01COg

**Comment by mstatt** [comment]
Has anyone provided a solution to this? I am having the same issue running locally. Followed step by step install instructions and downloaded the pretrained weights on Ubuntu.

**Comment by zzzweakman** [comment]
Thank you for your attention! Could you confirm that all the weights are placed in the correct location and that their sizes match those indicated in the [table](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#5-inference-speed-evaluation-) in the readme? @mstatt

**Comment by mstatt** [comment]
Yes, weights are in the correct location as instructed.

**Comment by mstatt** [comment]
The exact error: 
magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by Rizwanali324** [comment]
can you link the readme file for cloud deployments @FurkanGozukara also How can I deploy on Hugging Face as a Flask inference API? Are there specific steps or best practices I should follow to ensure a smooth deployment process?

**Comment by SGneil** [comment]
Sorry to see these messages now. I had problems downloading the weight files and training files. I forgot to install git lfs install first. After downloading, there was no problem.

**Comment by Rizwanali324** [comment]
> Sorry to see these messages now. I had problems downloading the weight files and training files. I forgot to install git lfs install first. After downloading, there was no problem, You can check this part.

thanks i have to deploy it in flutter as api .
can you point out me right direction how can i host it in any cloud or huggingface as inferance api
