### ISSUE TITLE
app.py doesnt show when the argument --share is applied

### ISSUE THREAD

**Issue by bulieme** [KwaiVGI/LivePortrait#70]
![image](https://github.com/KwaiVGI/LivePortrait/assets/53142287/d0dfaa2e-38db-4c39-a37c-18c3bf7da47f)

its been doing this on google colab, i dont know how

**Comment by bulieme** [comment]
it seems like `gradioPipeline` is blocking one of the share prints when `app.py` using it in `inference_cfg` variable

**Comment by bulieme** [comment]
idk if it has something to do with gradiopipeline

**Comment by FurkanGozukara** [comment]
i fixed it. works on Kaggle as well or you can give --share to start it on gradio live share

by the way google colab banned gradio live share for free accounts

https://github.com/KwaiVGI/LivePortrait/issues/78

**Comment by NeuralFalconYT** [comment]
Check Out This one it's working:
https://github.com/NeuralFalconYT/LivePortrait-Colab
