### ISSUE TITLE
using webcam video slows the inference

### ISSUE THREAD

**Issue by sirPhoebus** [KwaiVGI/LivePortrait#71]
Any idea why I have a slow-motion video as a result of the inference when I use a webcam video ?

**Comment by jaco001** [comment]
According to this...
https://github.com/KwaiVGI/LivePortrait/pull/30

try match your webcam to 30 fps

**Comment by zzzweakman** [comment]
> Any idea why I have a slow-motion video as a result of the inference when I use a webcam video ?

This issue occurs because we had fixed the output video's FPS to 30. We have addressed this in the latest version. Now, the output video's FPS matches the driving video's FPS : ) @sirPhoebus
