### ISSUE TITLE
Can you make it run on 127.0.0.1 instead of the 0.0.0.0 with public link?

### ISSUE THREAD

**Issue by boogertwilliams** [KwaiVGI/LivePortrait#72]
It cannot run on a company PC, Windows Defender blocks because of:
PUA:Win32/FRProxy

Can you make it jsut run on 127.0.0.1 like stable diffusion etc?

**Comment by Lesteriax** [comment]
Just go here /src/config/argument_config.py and edit below as you need

    ########## gradio arguments ##########
    server_port: Annotated[int, tyro.conf.arg(aliases=["-p"])]  = 8890
    share: bool = True
    server_name: str = "0.0.0.0"

**Comment by boogertwilliams** [comment]
Indeed! It works thanks.

**Comment by cleardusk** [comment]
Thanks for the @Lesteriax 's reply.
Or, you can specify the port by CLI.
"Can you make it jsut run on 127.0.0.1 like stable diffusion etc?" Could you refer to the original address/url, we want to use it as a reference.
