### ISSUE TITLE
LivePortrait 1-Click Installers and full tutorials for Windows and Cloud (useful for Mac users) (Massed Compute, RunPod and a free Kaggle Account)

### ISSUE THREAD

**Issue by FurkanGozukara** [KwaiVGI/LivePortrait#78]
I know there are a lot of experts around here that can install and use easily. But I have prepared solid tutorials for newbies and shown how to use this amazing top quality app LivePortrait. I have to say congrats to the developers.

I am also a researcher you can see my LinkedIn profile here but recently I am shifted into AI lectures : https://www.linkedin.com/in/furkangozukara/

Both Windows and Cloud tutorial has manually written (100% accurate) captions / subtitles. Also both have manually written by me very detailed video chapters.

# Windows LivePortrait Tutorial

**https://youtu.be/FPtpNrmuwXk**

### [**Animate Static Photos into Talking Videos with LivePortrait AI Compose Perfect Expressions Fast**](https://youtu.be/FPtpNrmuwXk)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/beNzm6ITK_5AnipzYt40Y.png)](https://youtu.be/FPtpNrmuwXk)

# Cloud LivePortrait Tutorial : Massed Compute, RunPod & Kaggle

**https://youtu.be/wG7oPp01COg**

### [**LivePortrait: No-GPU Cloud Tutorial - RunPod, MassedCompute & Free Kaggle Account - Animate Images**](https://youtu.be/wG7oPp01COg)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/fvWxGLUrIe5XWqP37OBfU.png)](https://youtu.be/wG7oPp01COg)

## Windows LivePortrait Tutorial Video Chapters

- 0:00 Introduction to LivePortrait: A cutting-edge open-source application for image-to-animation conversion
- 2:20 Step-by-step guide for downloading and installing the LivePortrait Gradio application on your device
- 3:27 System requirements and installation process for LivePortrait
- 4:07 Verifying the successful installation of required components
- 5:02 Confirming installation completion and preserving installation logs
- 5:37 Initiating the LivePortrait application post-installation
- 5:57 Showcase of supplementary resources: Portrait images, driving videos, and rendered outputs
- 7:28 Navigating the LivePortrait application interface
- 8:06 VRAM consumption analysis for generating a 73-second animation
- 8:33 Commencing the animation process for the initial image
- 8:50 Monitoring the animation generation progress
- 10:10 Completion of the first animated video render
- 10:24 Discussion on the resolution specifications of rendered animations
- 10:45 Examining the native output resolution of LivePortrait
- 11:27 Overview of custom enhancements and features implemented beyond the official demo
- 11:51 Default storage location for generated animated videos
- 12:35 Exploring the impact of the Relative Motion feature
- 13:41 Analyzing the effects of the Do Crop option
- 14:17 Understanding the functionality of the Paste Back feature
- 15:01 Demonstrating the influence of the Target Eyelid Open Ratio parameter
- 17:02 Instructions for joining the SECourses Discord community

## Cloud LivePortrait Tutorial Video Chapters

- 0:00 Introduction to LivePortrait: A cloud-based tutorial for state-of-the-art image-to-animation open-source application
- 2:26 Installation and utilization guide for LivePortrait on MassedCompute, featuring an exclusive discount code
- 4:28 Instructions for applying the special 50% discount coupon on MassedCompute
- 4:50 Configuration of ThinLinc client for accessing and operating the MassedCompute virtual machine
- 5:33 Setting up ThinLinc client's synchronization folder for file transfer between local and MassedCompute systems
- 6:20 Transferring installer files to the MassedCompute sync folder
- 6:39 Connecting to the initialized MassedCompute virtual machine and installing the LivePortrait application
- 9:22 Launching and operating LivePortrait on MassedCompute post-installation
- 10:20 Initiating a second instance of LivePortrait on the additional GPU in MassedCompute
- 12:20 Locating generated animation videos and bulk downloading to local storage
- 13:23 LivePortrait installation process on RunPod cloud service
- 14:54 Selecting the appropriate RunPod template
- 15:20 Configuring RunPod proxy access ports
- 16:21 Uploading installer files to RunPod's JupyterLab interface and commencing installation
- 17:07 Launching LivePortrait on RunPod post-installation
- 17:17 Starting a second LivePortrait instance on the additional GPU
- 17:31 Accessing LivePortrait via RunPod's proxy connection
- 17:55 Animating the initial image on RunPod using a 73-second driving video
- 18:27 Analysis of processing time for a 73-second video animation (highlighting the application's impressive speed)
- 18:41 Troubleshooting input upload errors with an example case
- 19:17 One-click download feature for all generated animations on RunPod
- 20:28 Monitoring the progress of animation generation
- 21:07 Guide to installing and utilizing LivePortrait for free on a Kaggle account, emphasizing its remarkable speed
- 24:10 Generating the first animation on Kaggle post-installation and launch
- 24:22 Importance of complete image and video uploads to avoid errors
- 24:35 Tracking animation status and progress on Kaggle
- 24:45 Resource utilization analysis: GPU, CPU, RAM, VRAM, and animation processing speed on Kaggle
- 25:05 Implementing the one-click download feature for all generated animations on Kaggle
- 26:12 Restarting LivePortrait on Kaggle without reinstallation
- 26:36 Instructions for joining the SECourses Discord community for support and discussions

**Comment by Inferencer** [comment]
This appears to be a very in-depth resource and I commend you for the effort you put into this

**Comment by zzzweakman** [comment]
@FurkanGozukara Thank you for your efforts to improve the user experience : ) We have also provided official 1-Click installers. The users can find more details [here](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#-updates).

**Comment by FurkanGozukara** [comment]
@zzzweakman thanks. still my installer self installs and compiles on user system into a python virtual environment (VENV) so not exactly same like pre-compiled :)

I have step by step tutorials for Python, C++ tools, FFMPEG and CUDA installation that will make even animal model work perfectly 

by the way for anyone who wonders I am keeping installers up to date with latest versions

![image](https://github.com/user-attachments/assets/6efe5538-d5f9-4c61-945d-5bd6c0d00713)

![screencapture-127-0-0-1-7861-2024-08-14-18_02_23](https://github.com/user-attachments/assets/4debfaa1-24ce-456a-928f-f9515863cc68)

![screencapture-127-0-0-1-7862-2024-08-14-18_03_43](https://github.com/user-attachments/assets/8f8eaa5b-2bf5-4cba-8d8b-ed5148e92195)

**Comment by Rizwanali324** [comment]
> I know there are a lot of experts around here that can install and use easily. But I have prepared solid tutorials for newbies and shown how to use this amazing top quality app LivePortrait. I have to say congrats to the developers.
> 
> I am also a researcher you can see my LinkedIn profile here but recently I am shifted into AI lectures : https://www.linkedin.com/in/furkangozukara/
> 
> Both Windows and Cloud tutorial has manually written (100% accurate) captions / subtitles. Also both have manually written by me very detailed video chapters.
> 
> # Windows LivePortrait Tutorial
> **https://youtu.be/FPtpNrmuwXk**
> 
> ### [**Animate Static Photos into Talking Videos with LivePortrait AI Compose Perfect Expressions Fast**](https://youtu.be/FPtpNrmuwXk)
> [![image](https://camo.githubusercontent.com/54cf223c12b409831be7f21cbb0cf11c8b5f4a352ca31cab546166f6984e7946/68747470733a2f2f63646e2d75706c6f6164732e68756767696e67666163652e636f2f70726f64756374696f6e2f75706c6f6164732f3633343562643839666531333464666437613064626134302f62654e7a6d3649544b5f35416e69707a59743430592e706e67)](https://youtu.be/FPtpNrmuwXk)
> 
> # Cloud LivePortrait Tutorial : Massed Compute, RunPod & Kaggle
> **https://youtu.be/wG7oPp01COg**
> 
> ### [**LivePortrait: No-GPU Cloud Tutorial - RunPod, MassedCompute & Free Kaggle Account - Animate Images**](https://youtu.be/wG7oPp01COg)
> [![image](https://camo.githubusercontent.com/d46a3dc9781a964b45065583f63afb71852434c8232b42de75d637416e89c434/68747470733a2f2f63646e2d75706c6f6164732e68756767696e67666163652e636f2f70726f64756374696f6e2f75706c6f6164732f3633343562643839666531333464666437613064626134302f66765778474c55724965355857715033374f4266552e706e67)](https://youtu.be/wG7oPp01COg)
> 
> ## Windows LivePortrait Tutorial Video Chapters
> * 0:00 Introduction to LivePortrait: A cutting-edge open-source application for image-to-animation conversion
> * 2:20 Step-by-step guide for downloading and installing the LivePortrait Gradio application on your device
> * 3:27 System requirements and installation process for LivePortrait
> * 4:07 Verifying the successful installation of required components
> * 5:02 Confirming installation completion and preserving installation logs
> * 5:37 Initiating the LivePortrait application post-installation
> * 5:57 Showcase of supplementary resources: Portrait images, driving videos, and rendered outputs
> * 7:28 Navigating the LivePortrait application interface
> * 8:06 VRAM consumption analysis for generating a 73-second animation
> * 8:33 Commencing the animation process for the initial image
> * 8:50 Monitoring the animation generation progress
> * 10:10 Completion of the first animated video render
> * 10:24 Discussion on the resolution specifications of rendered animations
> * 10:45 Examining the native output resolution of LivePortrait
> * 11:27 Overview of custom enhancements and features implemented beyond the official demo
> * 11:51 Default storage location for generated animated videos
> * 12:35 Exploring the impact of the Relative Motion feature
> * 13:41 Analyzing the effects of the Do Crop option
> * 14:17 Understanding the functionality of the Paste Back feature
> * 15:01 Demonstrating the influence of the Target Eyelid Open Ratio parameter
> * 17:02 Instructions for joining the SECourses Discord community
> 
> ## Cloud LivePortrait Tutorial Video Chapters
> * 0:00 Introduction to LivePortrait: A cloud-based tutorial for state-of-the-art image-to-animation open-source application
> * 2:26 Installation and utilization guide for LivePortrait on MassedCompute, featuring an exclusive discount code
> * 4:28 Instructions for applying the special 50% discount coupon on MassedCompute
> * 4:50 Configuration of ThinLinc client for accessing and operating the MassedCompute virtual machine
> * 5:33 Setting up ThinLinc client's synchronization folder for file transfer between local and MassedCompute systems
> * 6:20 Transferring installer files to the MassedCompute sync folder
> * 6:39 Connecting to the initialized MassedCompute virtual machine and installing the LivePortrait application
> * 9:22 Launching and operating LivePortrait on MassedCompute post-installation
> * 10:20 Initiating a second instance of LivePortrait on the additional GPU in MassedCompute
> * 12:20 Locating generated animation videos and bulk downloading to local storage
> * 13:23 LivePortrait installation process on RunPod cloud service
> * 14:54 Selecting the appropriate RunPod template
> * 15:20 Configuring RunPod proxy access ports
> * 16:21 Uploading installer files to RunPod's JupyterLab interface and commencing installation
> * 17:07 Launching LivePortrait on RunPod post-installation
> * 17:17 Starting a second LivePortrait instance on the additional GPU
> * 17:31 Accessing LivePortrait via RunPod's proxy connection
> * 17:55 Animating the initial image on RunPod using a 73-second driving video
> * 18:27 Analysis of processing time for a 73-second video animation (highlighting the application's impressive speed)
> * 18:41 Troubleshooting input upload errors with an example case
> * 19:17 One-click download feature for all generated animations on RunPod
> * 20:28 Monitoring the progress of animation generation
> * 21:07 Guide to installing and utilizing LivePortrait for free on a Kaggle account, emphasizing its remarkable speed
> * 24:10 Generating the first animation on Kaggle post-installation and launch
> * 24:22 Importance of complete image and video uploads to avoid errors
> * 24:35 Tracking animation status and progress on Kaggle
> * 24:45 Resource utilization analysis: GPU, CPU, RAM, VRAM, and animation processing speed on Kaggle
> * 25:05 Implementing the one-click download feature for all generated animations on Kaggle
> * 26:12 Restarting LivePortrait on Kaggle without reinstallation
> * 26:36 Instructions for joining the SECourses Discord community for support and discussions

how to run it on multiple GPU as on kaggle do I need to set device id as list if I have multiple GPU.?
i want to test on kaggle

**Comment by FurkanGozukara** [comment]
@Rizwanali324 it doesnt have dual gpu support. but you can run on single one it is working really fast

**Comment by Rizwanali324** [comment]
> @Rizwanali324 it doesnt have dual gpu support. but you can run on single one it is working really fast

the problem is that we use two methods preuploaded and custom uploaded(paid one in app)
which we dont know how long the video . and it should needs to fast render to keep customer on app..
but motion file did welll.
