### ISSUE TITLE
Does the video you generate also come under the MIT license?

### ISSUE THREAD

**Issue by nonnon1129** [KwaiVGI/LivePortrait#79]
Thank you for the great work. Does the video you generate also come under the MIT license?

**Comment by cleardusk** [comment]
The code and models are under MIT license, except for the models of InsightFace. But you can easily replace the face detection of InsightFace with other licensed models.
As for the results, I think the results generated by your own driven videos are not limited. The provided driving videos are mainly for showcases and research usage : )
