### ISSUE TITLE
Add this project's huggin face repo  in "Download pretrained weights" section of Readme

### ISSUE THREAD

**Issue by HakaishinShwet** [KwaiVGI/LivePortrait#84]
Reason for this is because google drive link gives continuous server error and wont let people download easily plus many english people wont understand baidu link and in some countries it might not even open so guide users to use hugginface repo to download models and all.I Faced issues so i researched for repo link which should be in readme but is not so please include this one - https://huggingface.co/KwaiVGI/LivePortrait

**Comment by cleardusk** [comment]
Thanks for you advice, we will add it! @HakaishinShwet
