### ISSUE TITLE
error during downloading requirements.txt

### ISSUE THREAD

**Issue by ALDIfreak** [KwaiVGI/LivePortrait#85]
Hello guys,
it seems like the download does not work when prompting:

pip install -r requirements.txt

it starts but always fails at 2.2GB/2.7GBs
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Collecting torch==2.3.0 (from -r requirements.txt (line 2))
  Downloading https://download.pytorch.org/whl/cu118/torch-2.3.0%2Bcu118-cp39-cp39-win_amd64.whl (2673.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 2.2/2.7 GB 11.9 MB/s eta 0:00:41

i also tried to download the file directly but getting the same error. has nothing to do with available space on my system.
could you have a look into the problem please?

thanks a lot!

**Comment by zzzweakman** [comment]
Thanks for your attention. Please follow the installation instructions provided [here](https://pytorch.org/get-started/previous-versions/#v230). @ALDIfreak

**Comment by ALDIfreak** [comment]
> Thanks for your attention. Please follow the installation instructions provided [here](https://pytorch.org/get-started/previous-versions/#v230). @ALDIfreak

thanks a lot for the quick response, trying to follow the steps there :)

**Comment by FurkanGozukara** [comment]
Use cloud flare vpn warp and try again

**Comment by Lesteriax** [comment]
> Use cloud flare vpn warp and try again

how do you do that?

**Comment by FurkanGozukara** [comment]
> > Use cloud flare vpn warp and try again
> 
> how do you do that?

Just type Google warn vpn, download, install, enable and install again
