### ISSUE TITLE
【Request feature】ONNX export support ？

### ISSUE THREAD

**Issue by juntaosun** [KwaiVGI/LivePortrait#86]
pretrained_weights/
Who can support exporting .pth to onnx ?

pretrained_weights
├── insightface
│   └── models
│       └── buffalo_l
│           ├── 2d106det.onnx
│           └── det_10g.onnx
└── liveportrait
    ├── base_models
    │   ├── appearance_feature_extractor.pth   👈✅
    │   ├── motion_extractor.pth  👈✅
    │   ├── spade_generator.pth  👈
    │   └── warping_module.pth  👈
    ├── landmark.onnx
    └── retargeting_models
        └── stitching_retargeting_module.pth  👈

I encountered some errors are：
OnnxExporterError: Unsupported: ONNX export of operator GridSample with 5D volumetric input.
Unable to complete export~

**Comment by zzzweakman** [comment]
Thank you for your attention! You can download the nightly version of [pytorch](https://pytorch.org/) to export the `.pth` model to `ONNX` format. You can find more details [here](https://github.com/pytorch/pytorch/issues/100790). However, unfortunately, based on our previous attempts, the `GridSample` operation is still not supported by the `CPUExecutionProvider` in the latest version of `onnxruntime-gpu`, thus inference acceleration might not be possible at this time. @juntaosun

**Comment by zzzweakman** [comment]
We also attempted to export the model to `TRT` format but encountered similar issues. Resolving these problems likely requires expertise in CUDA or model deployment, which is beyond our current capabilities. We hope this clarifies your question :) @juntaosun 

Additionally, we hope someone can address this issue, as it would significantly improve the inference speed of the project.

**Comment by aihacker111** [comment]
New Information: we already have 4 model convert to onnx: feature_extractor.onnx, motion_extractor.onnx, warping.onnx, spade_generator.onnx, but I need to convert stiching model -> 3 model onnx (eye sticht, lip sticht, all sticht)
