### ISSUE TITLE
can't install onnxruntime-gpu as per instructions

### ISSUE THREAD

**Issue by opinsky** [KwaiVGI/LivePortrait#87]
Mac M1Max on Sonoma 14.5

trying to setup as per the instructions. everything works fine up until 'pip install -r requirements.txt', which fails when trying to install onnxruntime-gpu, generating the following error message:

`ERROR: Ignored the following versions that require a different python version: 1.14.0 Requires-Python >=3.10; 1.14.0rc1 Requires-Python >=3.10; 1.14.0rc2 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.18.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu==1.18.`

I've also tried to setup a new environment with python 3.10.14, but the installation halts at the same place, with this error message:

`ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.18.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu==1.18.0`

**Comment by opinsky** [comment]
It looks like all the code was designed around CUDA - i've tried using the Mx GPU / MPS but this refactor is way above my coding skills.

**Comment by zzzweakman** [comment]
Hey there,

I wanted to point out that there's been some impressive work for CPU inference done on https://github.com/KwaiVGI/LivePortrait/issues/126. They've managed to get support for the M1 CPU. You might want to follow their progress as well. Great work is happening there : ） @opinsky @ExtremOPS

**Comment by zzzweakman** [comment]
Thank you for your patience, everyone. We are excited to inform you that LivePortrait now supports macOS with Apple Silicon! You can find more details [here](https://github.com/KwaiVGI/LivePortrait/commit/0f839844f60c72700fe80d380368355c29bf3435).

@opinsky @ExtremOPS
