### ISSUE TITLE
cv2.error: 

### ISSUE THREAD

**Issue by verolwh** [KwaiVGI/LivePortrait#99]
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2825: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

**Comment by zzzweakman** [comment]
> cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2825: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'

Hi, could you provide more details? For example, specify which line of code triggered this error : ) @verolwh

**Comment by zzzweakman** [comment]
This issue is similar to #138. All directory names from the root to the image directory must be in English only.
